export interface FreeMockQuestion {
  id: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  option_e: string;
  correct_option: 'a' | 'b' | 'c' | 'd' | 'e';
  subject?: string;
}

export const DEFAULT_FREE_MOCK_QUESTIONS: FreeMockQuestion[] = [
  // ─── 1. Logical Reasoning (Q1 - Q5) ───────────────────────────
  {
    id: 'fmock-01',
    subject: 'Logical Reasoning',
    question: 'All surgeons who operate at St. Jude Hospital must have completed a cardiothoracic fellowship or have at least ten years of general surgical experience. Dr. Vance operates at St. Jude Hospital and has only six years of general surgical experience. Which of the following conclusions must be true?',
    option_a: 'Dr. Vance is not a general surgeon.',
    option_b: 'Dr. Vance has completed a cardiothoracic fellowship.',
    option_c: 'Dr. Vance is the chief of surgery at St. Jude Hospital.',
    option_d: 'Dr. Vance will complete ten years of experience in four years.',
    option_e: 'No surgeon at St. Jude Hospital has fewer than six years of experience.',
    correct_option: 'b',
  },
  {
    id: 'fmock-02',
    subject: 'Logical Reasoning',
    question: 'A study showed that cities with more public swimming pools report higher rates of sunburn hospitalizations. The city council concluded that closing public swimming pools would directly reduce sunburn incidence. Which of the following best identifies the flaw in the council’s reasoning?',
    option_a: 'It assumes that swimming pool water causes sunburn directly.',
    option_b: 'It fails to consider that both sunny warm weather and outdoor pool visits correlate with sunlight exposure.',
    option_c: 'It ignores the financial impact of maintaining public recreational facilities.',
    option_d: 'It presumes that people who swim do not use protective sunscreen lotion.',
    option_e: 'It relies on hospital admission data rather than emergency room visits.',
    correct_option: 'b',
  },
  {
    id: 'fmock-03',
    subject: 'Logical Reasoning',
    question: 'If a patient exhibits symptoms of hyperkalemia, an immediate electrocardiogram (ECG) is indicated. Patient Morales underwent an emergency ECG this morning. Therefore, Patient Morales must have exhibited symptoms of hyperkalemia. Which of the following arguments displays the same logical flaw as the argument above?',
    option_a: 'If it rains, the grass gets wet. The grass is wet today, so it must have rained.',
    option_b: 'If an antibiotic is bactericidal, it kills bacteria. Penicillin kills bacteria, so it is bacteriostatic.',
    option_c: 'Whenever temperature drops below zero, water freezes. The water is not frozen, so the temperature is above zero.',
    option_d: 'All mammals are warm-blooded. A whale is a mammal, so it is warm-blooded.',
    option_e: 'If someone exercises daily, their stamina increases. John does not exercise daily, so his stamina has decreased.',
    correct_option: 'a',
  },
  {
    id: 'fmock-04',
    subject: 'Logical Reasoning',
    question: 'Five medical researchers (A, B, C, D, and E) work in consecutive offices along a straight hallway. Office 1 is at the far left and Office 5 is at the far right. B is directly adjacent to D. A is to the immediate left of C. E is in Office 1. D is in Office 3. Who is in Office 4?',
    option_a: 'A',
    option_b: 'B',
    option_c: 'C',
    option_d: 'D',
    option_e: 'E',
    correct_option: 'a',
  },
  {
    id: 'fmock-05',
    subject: 'Logical Reasoning',
    question: 'Which of the following, if true, most seriously weakens the argument that prescribing generic statins instead of brand-name statins consistently lowers total healthcare costs?',
    option_a: 'Brand-name statins are widely advertised on television and social media.',
    option_b: 'Some patients prescribed generic statins experience minor inactive ingredient intolerance requiring expensive specialist visits.',
    option_c: 'Generic statins contain the identical active pharmaceutical compound as brand formulations.',
    option_d: 'Physicians receive identical clinical trial guidelines for generic and branded statins.',
    option_e: 'Pharmacies generally retain higher profit margins on generic medications.',
    correct_option: 'b',
  },

  // ─── 2. Reading Skills & Acquired Knowledge (Q6 - Q9) ─────────
  {
    id: 'fmock-06',
    subject: 'Reading Skills & Acquired Knowledge',
    question: 'In the history of medicine, who was awarded the Nobel Prize in Physiology or Medicine in 1945 alongside Ernst Chain and Howard Florey for the discovery and development of penicillin?',
    option_a: 'Louis Pasteur',
    option_b: 'Alexander Fleming',
    option_c: 'Robert Koch',
    option_d: 'Edward Jenner',
    option_e: 'Joseph Lister',
    correct_option: 'b',
  },
  {
    id: 'fmock-07',
    subject: 'Reading Skills & Acquired Knowledge',
    question: 'Which international treaty, adopted in 1948 by the United Nations General Assembly in Paris, first articulated fundamental human rights to be universally protected?',
    option_a: 'Treaty of Versailles',
    option_b: 'Universal Declaration of Human Rights',
    option_c: 'Geneva Convention',
    option_d: 'Maastricht Treaty',
    option_e: 'Nuremberg Code',
    correct_option: 'b',
  },
  {
    id: 'fmock-08',
    subject: 'Reading Skills & Acquired Knowledge',
    question: 'Read the following passage: "The human microbiome comprises trillions of microbial cells whose metabolic products profoundly influence human neurodevelopment, immune regulation, and endocrine signaling via the gut-brain axis." According to the passage, the microbiome:',
    option_a: 'Operates exclusively within the mucosal layer of the large intestine without systemic influence.',
    option_b: 'Exerts multi-systemic effects through metabolites communicating across organ networks.',
    option_c: 'Replaces endogenous neurotransmitter synthesis in the central nervous system completely.',
    option_d: 'Causes irreversible endocrine dysregulation whenever bacterial diversity increases.',
    option_e: 'Is primarily responsible for structural skeletal remodeling during early childhood.',
    correct_option: 'b',
  },
  {
    id: 'fmock-09',
    subject: 'Reading Skills & Acquired Knowledge',
    question: 'Which author wrote the seminal literary work "The Divine Comedy" (La Divina Commedia), marking a cornerstone of Italian and Western literature?',
    option_a: 'Giovanni Boccaccio',
    option_b: 'Dante Alighieri',
    option_c: 'Francesco Petrarca',
    option_d: 'Niccolò Machiavelli',
    option_e: 'Ludovico Ariosto',
    correct_option: 'b',
  },

  // ─── 3. Biology (Q10 - Q32, 23 Questions) ──────────────────────
  {
    id: 'fmock-10',
    subject: 'Biology',
    question: 'Which organelle is bounded by a double membrane and contains its own circular DNA and 70S ribosomes?',
    option_a: 'Golgi apparatus',
    option_b: 'Mitochondrion',
    option_c: 'Lysosome',
    option_d: 'Rough endoplasmic reticulum',
    option_e: 'Peroxisome',
    correct_option: 'b',
  },
  {
    id: 'fmock-11',
    subject: 'Biology',
    question: 'During which phase of the eukaryotic cell cycle does DNA replication occur?',
    option_a: 'G1 phase',
    option_b: 'S phase',
    option_c: 'G2 phase',
    option_d: 'Metaphase',
    option_e: 'Anaphase',
    correct_option: 'b',
  },
  {
    id: 'fmock-12',
    subject: 'Biology',
    question: 'What is the primary function of DNA topoisomerase (gyrase) during replication?',
    option_a: 'Synthesize RNA primers on the lagging strand.',
    option_b: 'Relieve torsional strain and supercoiling ahead of the replication fork.',
    option_c: 'Form phosphodiester bonds between adjacent Okazaki fragments.',
    option_d: 'Prevent single-stranded DNA from re-annealing.',
    option_e: 'Proofread newly incorporated nucleotides using 3\' to 5\' exonuclease activity.',
    correct_option: 'b',
  },
  {
    id: 'fmock-13',
    subject: 'Biology',
    question: 'Which of the following processes in cellular respiration yields carbon dioxide (CO2)?',
    option_a: 'Glycolysis only',
    option_b: 'Pyruvate decarboxylation (link reaction) and the Krebs cycle',
    option_c: 'Oxidative phosphorylation across the inner mitochondrial membrane',
    option_d: 'Lactic acid fermentation in skeletal muscle',
    option_e: 'Gluconeogenesis in hepatocytes',
    correct_option: 'b',
  },
  {
    id: 'fmock-14',
    subject: 'Biology',
    question: 'In human genetics, Huntington\'s disease is an autosomal dominant disorder. If one parent is heterozygous for the Huntington allele and the other parent is unaffected, what is the probability that their child will inherit the disorder?',
    option_a: '0%',
    option_b: '25%',
    option_c: '50%',
    option_d: '75%',
    option_e: '100%',
    correct_option: 'c',
  },
  {
    id: 'fmock-15',
    subject: 'Biology',
    question: 'Which enzyme is responsible for synthesizing ribosomal RNA (rRNA) inside the nucleolus of eukaryotic cells?',
    option_a: 'RNA Polymerase I',
    option_b: 'RNA Polymerase II',
    option_c: 'RNA Polymerase III',
    option_d: 'DNA Polymerase alpha',
    option_e: 'Reverse Transcriptase',
    correct_option: 'a',
  },
  {
    id: 'fmock-16',
    subject: 'Biology',
    question: 'Which of the following blood vessels carries oxygen-rich blood from the lungs into the left atrium of the human heart?',
    option_a: 'Superior vena cava',
    option_b: 'Pulmonary veins',
    option_c: 'Pulmonary arteries',
    option_d: 'Aorta',
    option_e: 'Coronary sinus',
    correct_option: 'b',
  },
  {
    id: 'fmock-17',
    subject: 'Biology',
    question: 'During synaptic transmission, the influx of which ion into the presynaptic terminal triggers the exocytosis of neurotransmitter vesicles?',
    option_a: 'Sodium (Na+)',
    option_b: 'Calcium (Ca2+)',
    option_c: 'Potassium (K+)',
    option_d: 'Chloride (Cl-)',
    option_e: 'Magnesium (Mg2+)',
    correct_option: 'b',
  },
  {
    id: 'fmock-18',
    subject: 'Biology',
    question: 'Which endocrine hormone is secreted by the alpha cells of the pancreatic islets of Langerhans to raise blood glucose concentrations?',
    option_a: 'Insulin',
    option_b: 'Glucagon',
    option_c: 'Somatostatin',
    option_d: 'Aldosterone',
    option_e: 'Cortisol',
    correct_option: 'b',
  },
  {
    id: 'fmock-19',
    subject: 'Biology',
    question: 'In the nephron, the majority of filtered water, sodium, amino acids, and glucose is reabsorbed in the:',
    option_a: 'Glomerular capsule (Bowman’s capsule)',
    option_b: 'Proximal convoluted tubule (PCT)',
    option_c: 'Descending limb of the loop of Henle',
    option_d: 'Distal convoluted tubule (DCT)',
    option_e: 'Medullary collecting duct',
    correct_option: 'b',
  },
  {
    id: 'fmock-20',
    subject: 'Biology',
    question: 'Which immunoglobulin is the most abundant in human serum and is capable of crossing the placental barrier to confer passive immunity to the fetus?',
    option_a: 'IgA',
    option_b: 'IgD',
    option_c: 'IgE',
    option_d: 'IgG',
    option_e: 'IgM',
    correct_option: 'd',
  },
  {
    id: 'fmock-21',
    subject: 'Biology',
    question: 'What is the primary function of the surfactant secreted by type II pneumocytes in pulmonary alveoli?',
    option_a: 'Facilitate active transport of carbon dioxide into the blood.',
    option_b: 'Decrease alveolar surface tension and prevent alveolar collapse during expiration.',
    option_c: 'Destroy inhaled bacterial pathogens through enzymatic lysis.',
    option_d: 'Humidify inspired air in the conducting airways.',
    option_e: 'Bind free oxygen molecules to increase partial pressure.',
    correct_option: 'b',
  },
  {
    id: 'fmock-22',
    subject: 'Biology',
    question: 'Which of the following structures in skeletal muscle fibers releases calcium ions into the sarcoplasm to initiate muscle contraction?',
    option_a: 'Sarcolemma',
    option_b: 'Sarcoplasmic reticulum',
    option_c: 'T-tubules',
    option_d: 'Tropomyosin filaments',
    option_e: 'Myosin heads',
    correct_option: 'b',
  },
  {
    id: 'fmock-23',
    subject: 'Biology',
    question: 'A codon on mRNA reads 5\'-AUG-3\'. What is the corresponding anticodon sequence on the initiator tRNA (written in 5\' to 3\' direction)?',
    option_a: '5\'-UAC-3\'',
    option_b: '5\'-CAU-3\'',
    option_c: '5\'-GUA-3\'',
    option_d: '5\'-TAC-3\'',
    option_e: '5\'-AUG-3\'',
    correct_option: 'b',
  },
  {
    id: 'fmock-24',
    subject: 'Biology',
    question: 'Which metabolic pathway converts glucose into pyruvate under anaerobic conditions in the cytosol without requiring oxygen?',
    option_a: 'Beta-oxidation',
    option_b: 'Glycolysis',
    option_c: 'Krebs cycle',
    option_d: 'Pentose phosphate pathway',
    option_e: 'Oxidative phosphorylation',
    correct_option: 'b',
  },
  {
    id: 'fmock-25',
    subject: 'Biology',
    question: 'What type of junction between cardiac muscle cells allows the rapid passage of action potentials from cell to cell, functioning as an electrical syncytium?',
    option_a: 'Tight junctions (zonula occludens)',
    option_b: 'Gap junctions (nexus)',
    option_c: 'Desmosomes (macula adherens)',
    option_d: 'Hemidesmosomes',
    option_e: 'Adherens junctions',
    correct_option: 'b',
  },
  {
    id: 'fmock-26',
    subject: 'Biology',
    question: 'Which segment of the human gastrointestinal tract is the principal anatomical site for lipid emulsification and enzymatic digestion by pancreatic lipase?',
    option_a: 'Stomach corpus',
    option_b: 'Duodenum',
    option_c: 'Terminal ileum',
    option_d: 'Ascending colon',
    option_e: 'Esophagus',
    correct_option: 'b',
  },
  {
    id: 'fmock-27',
    subject: 'Biology',
    question: 'Crossing over (homologous genetic recombination) occurs during which specific stage of meiosis?',
    option_a: 'Prophase I (Pachytene)',
    option_b: 'Metaphase I',
    option_c: 'Anaphase I',
    option_d: 'Prophase II',
    option_e: 'Telophase II',
    correct_option: 'a',
  },
  {
    id: 'fmock-28',
    subject: 'Biology',
    question: 'Which type of RNA molecule carries amino acids to the ribosome during peptide elongation?',
    option_a: 'Messenger RNA (mRNA)',
    option_b: 'Transfer RNA (tRNA)',
    option_c: 'Ribosomal RNA (rRNA)',
    option_d: 'Small nuclear RNA (snRNA)',
    option_e: 'MicroRNA (miRNA)',
    correct_option: 'b',
  },
  {
    id: 'fmock-29',
    subject: 'Biology',
    question: 'In the ABO blood typing system, an individual with phenotype AB blood produces:',
    option_a: 'Anti-A antibodies only in their plasma.',
    option_b: 'Neither anti-A nor anti-B antibodies in their plasma.',
    option_c: 'Both anti-A and anti-B antibodies in their plasma.',
    option_d: 'Anti-B antibodies only in their plasma.',
    option_e: 'Anti-O antibodies in their plasma.',
    correct_option: 'b',
  },
  {
    id: 'fmock-30',
    subject: 'Biology',
    question: 'What is the main role of the enzyme DNA ligase in recombinant DNA technology and molecular replication?',
    option_a: 'Cleave DNA at specific palindromic recognition sequences.',
    option_b: 'Synthesize single-stranded cDNA from an mRNA template.',
    option_c: 'Catalyze the formation of covalent phosphodiester bonds between adjacent 3\'-OH and 5\'-phosphate termini.',
    option_d: 'Unwind double-stranded DNA using ATP hydrolysis.',
    option_e: 'Add poly-A tails to eukaryotic transcripts.',
    correct_option: 'c',
  },
  {
    id: 'fmock-31',
    subject: 'Biology',
    question: 'Which vitamin is essential as a cofactor for the post-translational carboxylation of clotting factors II, VII, IX, and X in the liver?',
    option_a: 'Vitamin A',
    option_b: 'Vitamin C',
    option_c: 'Vitamin D',
    option_d: 'Vitamin K',
    option_e: 'Vitamin B12',
    correct_option: 'd',
  },
  {
    id: 'fmock-32',
    subject: 'Biology',
    question: 'Which anterior pituitary hormone directly stimulates thyroid gland follicular cells to produce thyroxine (T4) and triiodothyronine (T3)?',
    option_a: 'Adrenocorticotropic hormone (ACTH)',
    option_b: 'Thyroid-stimulating hormone (TSH)',
    option_c: 'Growth hormone (GH)',
    option_d: 'Luteinizing hormone (LH)',
    option_e: 'Prolactin',
    correct_option: 'b',
  },

  // ─── 4. Chemistry (Q33 - Q47, 15 Questions) ───────────────────
  {
    id: 'fmock-33',
    subject: 'Chemistry',
    question: 'What is the total number of valence electrons in the nitrate ion (NO3-)? [Atomic numbers: N = 7, O = 8]',
    option_a: '22',
    option_b: '23',
    option_c: '24',
    option_d: '26',
    option_e: '32',
    correct_option: 'c',
  },
  {
    id: 'fmock-34',
    subject: 'Chemistry',
    question: 'Which of the following elements has the greatest first ionization energy in the periodic table?',
    option_a: 'Lithium (Li)',
    option_b: 'Helium (He)',
    option_c: 'Fluorine (F)',
    option_d: 'Cesium (Cs)',
    option_e: 'Neon (Ne)',
    correct_option: 'b',
  },
  {
    id: 'fmock-35',
    subject: 'Chemistry',
    question: 'What is the pH of a 0.001 M aqueous solution of hydrochloric acid (HCl) at 25 °C?',
    option_a: '1',
    option_b: '2',
    option_c: '3',
    option_d: '4',
    option_e: '11',
    correct_option: 'c',
  },
  {
    id: 'fmock-36',
    subject: 'Chemistry',
    question: 'According to Le Chatelier\'s principle, what will happen to the equilibrium of the exothermic reaction 2SO2(g) + O2(g) <=> 2SO3(g) [Delta H < 0] if the temperature is increased at constant volume?',
    option_a: 'The equilibrium shifts to the right, increasing SO3 yield.',
    option_b: 'The equilibrium shifts to the left, decreasing SO3 yield.',
    option_c: 'No shift occurs because pressure remains constant.',
    option_d: 'The equilibrium constant Kc increases.',
    option_e: 'Both SO2 and SO3 concentrations decrease equally.',
    correct_option: 'b',
  },
  {
    id: 'fmock-37',
    subject: 'Chemistry',
    question: 'What is the oxidation state of chromium in the dichromate ion, Cr2O7^(2-)?',
    option_a: '+3',
    option_b: '+4',
    option_c: '+5',
    option_d: '+6',
    option_e: '+7',
    correct_option: 'd',
  },
  {
    id: 'fmock-38',
    subject: 'Chemistry',
    question: 'Which geometric shape is predicted by VSEPR theory for the water (H2O) molecule?',
    option_a: 'Linear',
    option_b: 'Trigonal planar',
    option_c: 'Bent (approx. 104.5 degrees)',
    option_d: 'Tetrahedral',
    option_e: 'Trigonal pyramidal',
    correct_option: 'c',
  },
  {
    id: 'fmock-39',
    subject: 'Chemistry',
    question: 'What type of chemical bond connects the amino group of one amino acid to the carboxyl group of another in a primary polypeptide chain?',
    option_a: 'Disulfide bond',
    option_b: 'Peptide (amide) bond',
    option_c: 'Glycosidic bond',
    option_d: 'Phosphodiester bond',
    option_e: 'Hydrogen bond',
    correct_option: 'b',
  },
  {
    id: 'fmock-40',
    subject: 'Chemistry',
    question: 'How many constitutional (structural) isomers exist for the molecular formula C4H10 (butane)?',
    option_a: '1',
    option_b: '2',
    option_c: '3',
    option_d: '4',
    option_e: '5',
    correct_option: 'b',
  },
  {
    id: 'fmock-41',
    subject: 'Chemistry',
    question: 'In the reaction: 2H2 + O2 -> 2H2O, which substance undergoes oxidation?',
    option_a: 'Hydrogen (H2)',
    option_b: 'Oxygen (O2)',
    option_c: 'Water (H2O)',
    option_d: 'Neither, because no electrons are transferred.',
    option_e: 'Both substances undergo reduction simultaneously.',
    correct_option: 'a',
  },
  {
    id: 'fmock-42',
    subject: 'Chemistry',
    question: 'What volume in liters does 1 mole of an ideal gas occupy at standard temperature and pressure (STP: 0 °C and 1 atm)?',
    option_a: '11.2 L',
    option_b: '22.4 L',
    option_c: '24.5 L',
    option_d: '44.8 L',
    option_e: '1.0 L',
    correct_option: 'b',
  },
  {
    id: 'fmock-43',
    subject: 'Chemistry',
    question: 'Which of the following organic functional groups contains a carbonyl group bonded directly to both an oxygen atom and a carbon atom (R-COO-R\')?',
    option_a: 'Ether',
    option_b: 'Ester',
    option_c: 'Aldehyde',
    option_d: 'Amide',
    option_e: 'Ketone',
    correct_option: 'b',
  },
  {
    id: 'fmock-44',
    subject: 'Chemistry',
    question: 'What is the molar mass of sulfuric acid, H2SO4? [Atomic masses: H = 1.0, S = 32.0, O = 16.0 g/mol]',
    option_a: '49.0 g/mol',
    option_b: '82.0 g/mol',
    option_c: '98.0 g/mol',
    option_d: '102.0 g/mol',
    option_e: '128.0 g/mol',
    correct_option: 'c',
  },
  {
    id: 'fmock-45',
    subject: 'Chemistry',
    question: 'Which of the following represents a conjugate acid-base pair according to the Bronsted-Lowry definition?',
    option_a: 'HCl and NaOH',
    option_b: 'H2CO3 and HCO3-',
    option_c: 'NH4+ and Cl-',
    option_d: 'H3O+ and OH-',
    option_e: 'H2SO4 and SO4^(2-)',
    correct_option: 'b',
  },
  {
    id: 'fmock-46',
    subject: 'Chemistry',
    question: 'Which quantum number determines the spatial orientation of an orbital in an atom?',
    option_a: 'Principal quantum number (n)',
    option_b: 'Azimuthal / orbital angular momentum quantum number (l)',
    option_c: 'Magnetic quantum number (ml)',
    option_d: 'Electron spin quantum number (ms)',
    option_e: 'Total angular momentum quantum number (j)',
    correct_option: 'c',
  },
  {
    id: 'fmock-47',
    subject: 'Chemistry',
    question: 'An element has the electron configuration [Ne] 3s2 3p4. To which group and period of the periodic table does this element belong?',
    option_a: 'Period 3, Group 14 (IVA)',
    option_b: 'Period 3, Group 16 (VIA / Chalcogens)',
    option_c: 'Period 4, Group 16 (VIA)',
    option_d: 'Period 2, Group 16 (VIA)',
    option_e: 'Period 3, Group 17 (Halogens)',
    correct_option: 'b',
  },

  // ─── 5. Physics & Mathematics (Q48 - Q60, 13 Questions) ────────
  {
    id: 'fmock-48',
    subject: 'Physics & Mathematics',
    question: 'A vehicle accelerates uniformly from rest at a constant acceleration of 3.0 m/s^2 along a straight highway. What distance does it travel during the first 6.0 seconds?',
    option_a: '18 m',
    option_b: '36 m',
    option_c: '54 m',
    option_d: '72 m',
    option_e: '108 m',
    correct_option: 'c',
  },
  {
    id: 'fmock-49',
    subject: 'Physics & Mathematics',
    question: 'What is the net work done on an object of mass 4.0 kg when its velocity increases from 2.0 m/s to 6.0 m/s on a frictionless surface?',
    option_a: '32 J',
    option_b: '64 J',
    option_c: '80 J',
    option_d: '144 J',
    option_e: '16 J',
    correct_option: 'b',
  },
  {
    id: 'fmock-50',
    subject: 'Physics & Mathematics',
    question: 'Two resistors of resistance R1 = 6 ohms and R2 = 12 ohms are connected in parallel across an ideal 12 V battery. What is the total current supplied by the battery?',
    option_a: '1.0 A',
    option_b: '2.0 A',
    option_c: '3.0 A',
    option_d: '4.0 A',
    option_e: '6.0 A',
    correct_option: 'c',
  },
  {
    id: 'fmock-51',
    subject: 'Physics & Mathematics',
    question: 'According to Snell\'s Law of refraction, if light travels from air (n1 = 1.0) into a transparent medium with refractive index n2 = 1.5 at an angle of incidence of 30 degrees, what is sin(theta_r)?',
    option_a: '1/3 (approx. 0.333)',
    option_b: '1/2 (0.500)',
    option_c: '3/4 (0.750)',
    option_d: 'sqrt(3)/3',
    option_e: '2/3',
    correct_option: 'a',
  },
  {
    id: 'fmock-52',
    subject: 'Physics & Mathematics',
    question: 'What is the buoyant force acting on a completely submerged spherical solid of volume 0.002 m^3 placed in pure water (density rho = 1000 kg/m^3, g = 9.8 m/s^2)?',
    option_a: '2.0 N',
    option_b: '19.6 N',
    option_c: '49.0 N',
    option_d: '98.0 N',
    option_e: '196.0 N',
    correct_option: 'b',
  },
  {
    id: 'fmock-53',
    subject: 'Physics & Mathematics',
    question: 'Which of the following expressions correctly states Coulomb\'s Law for the electrostatic force F between two point charges q1 and q2 separated by distance r in a vacuum?',
    option_a: 'F = k * |q1 * q2| / r',
    option_b: 'F = k * |q1 * q2| / r^2',
    option_c: 'F = k * (q1 + q2) / r^2',
    option_d: 'F = k * |q1 * q2|^2 / r',
    option_e: 'F = k * r^2 / |q1 * q2|',
    correct_option: 'b',
  },
  {
    id: 'fmock-54',
    subject: 'Physics & Mathematics',
    question: 'Solve for x in the quadratic equation: 2x^2 - 7x + 3 = 0.',
    option_a: 'x = 1/2 or x = 3',
    option_b: 'x = -1/2 or x = -3',
    option_c: 'x = 1 or x = 3/2',
    option_d: 'x = 2 or x = 7/2',
    option_e: 'x = -1 or x = 6',
    correct_option: 'a',
  },
  {
    id: 'fmock-55',
    subject: 'Physics & Mathematics',
    question: 'What is the value of log_2(32) + log_3(81)?',
    option_a: '7',
    option_b: '8',
    option_c: '9',
    option_d: '10',
    option_e: '11',
    correct_option: 'c',
  },
  {
    id: 'fmock-56',
    subject: 'Physics & Mathematics',
    question: 'In a right-angled triangle ABC with the right angle at C, if sin(A) = 3/5, what is the value of tan(A)?',
    option_a: '3/4',
    option_b: '4/3',
    option_c: '4/5',
    option_d: '5/3',
    option_e: '3/8',
    correct_option: 'a',
  },
  {
    id: 'fmock-57',
    subject: 'Physics & Mathematics',
    question: 'Two fair six-sided dice are rolled simultaneously. What is the probability that the sum of the numbers showing on top is equal to 7?',
    option_a: '1/12',
    option_b: '1/6',
    option_c: '5/36',
    option_d: '7/36',
    option_e: '1/4',
    correct_option: 'b',
  },
  {
    id: 'fmock-58',
    subject: 'Physics & Mathematics',
    question: 'What is the equation of the line passing through the points (2, 5) and (4, 11) in the Cartesian plane?',
    option_a: 'y = 2x + 1',
    option_b: 'y = 3x - 1',
    option_c: 'y = 3x + 1',
    option_d: 'y = 4x - 3',
    option_e: 'y = 6x - 7',
    correct_option: 'b',
  },
  {
    id: 'fmock-59',
    subject: 'Physics & Mathematics',
    question: 'A simple pendulum has an oscillation period T on Earth. If the length of the string is quadrupled (multiplied by 4) while keeping gravitational acceleration constant, what is the new period?',
    option_a: 'T/2',
    option_b: 'T',
    option_c: '2T',
    option_d: '4T',
    option_e: '16T',
    correct_option: 'c',
  },
  {
    id: 'fmock-60',
    subject: 'Physics & Mathematics',
    question: 'What is the sum of the first 10 terms of an arithmetic progression whose first term a1 = 3 and common difference d = 4?',
    option_a: '190',
    option_b: '210',
    option_c: '230',
    option_d: '250',
    option_e: '390',
    correct_option: 'b',
  },
];
