import {
  Course,
  Test,
  University,
  Scholarship,
  Mentor,
  DoubtItem,
  Lead,
  ApplicationCase,
  StudentDocument,
  VisaCase,
  AuditLogItem,
  Profile,
  ScheduleItem,
  RecordedLecture,
  LibraryResource,
  StudentMistake,
} from '@/types';

export const mockCurrentUser: Profile = {
  id: 'usr-student-01',
  role: 'student',
  firstName: 'Student',
  lastName: 'User',
  email: 'student@ahsora.com',
  phone: '+1 (555) 000-0000',
  country: 'Pakistan',
  city: 'Lahore',
  targetExam: 'IMAT (Italy)',
  targetCountry: 'Italy',
  isVerified: true,
  selectedPackage: 'Ahsora IMAT Ascend',
  packagePrice: '€299',
  createdAt: '2026-01-15T09:00:00Z',
};

export const mockCourses: Course[] = [
  {
    id: 'crs-01',
    slug: 'usmle-step-1-complete-mastery',
    title: 'USMLE Step 1: Clinical Integrated High-Yield Mastery',
    category: 'Medical Licensure',
    targetExam: 'IMAT / USMLE Step 1',
    summary: 'Organ systems, pharmacology, pathology, and high-yield question breakdowns with top US residency mentors.',
    overview: 'This comprehensive course provides an organ-systems approach with integrated pathology, pharmacology, and physiology. Designed for medical students targeting top residency percentiles.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    durationHours: 140,
    totalLectures: 86,
    totalTests: 12,
    totalResources: 45,
    rating: 4.96,
    studentsCount: 1420,
    price: 699,
    comparePrice: 999,
    isFeatured: true,
    badge: 'Bestseller',
    modules: [
      {
        id: 'mod-01',
        title: 'Cardiovascular Pathology & Hemodynamics',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-01',
            title: 'Ischemic Heart Disease: EKG & Biomarkers',
            durationMinutes: 42,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            contentMarkdown: '### Key Concepts in Ischemic Heart Disease\n\n1. **STEMI vs NSTEMI**\n- Transmural vs subendocardial infarction.\n- Troponin I and T rise within 2-4 hours, peak at 24 hours, persist for 7-10 days.\n\n2. **EKG Localization**\n- Anterior (LAD): V1-V4\n- Lateral (LCX): I, aVL, V5, V6\n- Inferior (RCA): II, III, aVF',
            isPreviewAllowed: true,
            isCompleted: true,
            orderIndex: 1,
          },
          {
            id: 'les-02',
            title: 'Valvular Heart Disease & Murmur Diagnostics',
            durationMinutes: 38,
            videoUrl: '',
            contentMarkdown: '### Systolic vs Diastolic Murmurs\n\n- **Aortic Stenosis**: Crescendo-decrescendo systolic ejection murmur at right 2nd ICS radiating to carotids.\n- **Mitral Regurgitation**: Holosystolic, high-pitched "blowing" murmur best heard at apex radiating to axilla.',
            isPreviewAllowed: false,
            isCompleted: true,
            orderIndex: 2,
          },
          {
            id: 'les-03',
            title: 'Heart Failure & Renin-Angiotensin System',
            durationMinutes: 50,
            videoUrl: '',
            contentMarkdown: '### Pathophysiology of Congestive Heart Failure\n\nDecreased cardiac output activates the sympathetic nervous system and the RAAS axis.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 3,
          },
        ],
      },
      {
        id: 'mod-02',
        title: 'Renal & Acid-Base Physiology',
        orderIndex: 2,
        lessons: [
          {
            id: 'les-04',
            title: 'Glomerular Filtration Rate & Clearance Mechanics',
            durationMinutes: 35,
            videoUrl: '',
            contentMarkdown: '### GFR and Renal Clearance Equations\n\nClearance = (Urine Concentration * Urine Flow) / Plasma Concentration.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 1,
          },
          {
            id: 'les-05',
            title: 'High Anion Gap Metabolic Acidosis (MUDPILES)',
            durationMinutes: 44,
            videoUrl: '',
            contentMarkdown: '### MUDPILES Differential Diagnosis\nMethanol, Uremia, DKA, Propylene glycol, Iron/INH, Lactic acidosis, Ethylene glycol, Salicylates.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'crs-02',
    slug: 'imat-italy-medical-entrance-prep',
    title: 'IMAT Italy: Complete Public Medical University Prep',
    category: 'Medical Admissions',
    targetExam: 'IMAT (Italy)',
    summary: 'Biology, Chemistry, Physics, Math, and Critical Reasoning specifically tailored to the Italian Ministry of Education entrance exam.',
    overview: 'Official preparation program for admission to English-taught medical faculties across Italy (Milan, Rome La Sapienza, Bologna, Pavia, Padua).',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&auto=format&fit=crop&q=80',
    durationHours: 110,
    totalLectures: 64,
    totalTests: 18,
    totalResources: 38,
    rating: 4.94,
    studentsCount: 980,
    price: 499,
    comparePrice: 750,
    isFeatured: true,
    badge: 'Popular',
    modules: [
      {
        id: 'mod-10',
        title: 'Cellular Biology & Molecular Genetics',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-10',
            title: 'Mendelian Genetics & Non-Mendelian Inheritance',
            durationMinutes: 30,
            isPreviewAllowed: true,
            isCompleted: true,
            orderIndex: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'crs-03',
    slug: 'plab-1-uk-gmc-registration-masterclass',
    title: 'PLAB 1 / UKMLA Clinical Knowledge Masterclass',
    category: 'Medical Licensure',
    targetExam: 'IMAT / PLAB 1',
    summary: 'NICE guidelines, GMC Good Medical Practice, emergency management, and single-best-answer strategy for UK practice.',
    overview: 'Targeted preparation for international medical graduates aiming to practice within the UK National Health Service (NHS).',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80',
    durationHours: 95,
    totalLectures: 52,
    totalTests: 10,
    totalResources: 30,
    rating: 4.91,
    studentsCount: 820,
    price: 449,
    comparePrice: 599,
    isFeatured: false,
    badge: 'NHS Aligned',
    modules: [],
  },
  {
    id: 'crs-04',
    slug: 'medical-german-b2-c1-approbation',
    title: 'Medical German B2/C1 & FSP Approbation Program',
    category: 'Language & Residency',
    targetExam: 'IMAT / FSP Germany',
    summary: 'Doctor-patient communication, medical history taking (Anamnese), and clinical documentation for German medical licensure.',
    overview: 'Comprehensive preparation for the Fachsprachenprüfung (FSP) and Kenntnisprüfung (KP) for medical residency in Germany.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    durationHours: 120,
    totalLectures: 70,
    totalTests: 8,
    totalResources: 50,
    rating: 4.98,
    studentsCount: 610,
    price: 799,
    comparePrice: 1100,
    isFeatured: true,
    badge: 'High Demand',
    modules: [],
  },
];

export const mockTests: Test[] = [
  {
    id: 'tst-01',
    slug: 'usmle-step-1-diagnostic-mock-01',
    title: 'USMLE Step 1 Full Diagnostic Assessment - Block 1',
    category: 'USMLE Step 1',
    subject: 'Integrated Medical Sciences',
    difficulty: 'hard',
    durationMinutes: 45,
    totalQuestions: 6,
    totalMarks: 24,
    positiveMark: 4,
    negativeMark: 1,
    passingPercentage: 60,
    instructions: 'This block contains 6 high-yield vignette questions. Timed at 45 minutes with standard 1-minute/question pacing. Negative marking is applied (-1 for incorrect, +4 for correct).',
    isPublicSample: true,
    questions: [
      {
        id: 'q-01',
        orderIndex: 1,
        subject: 'Pathology & Pharmacology',
        topic: 'Cardiovascular',
        difficulty: 'hard',
        questionText: 'A 58-year-old male presents with severe retrosternal chest tightness radiating to the left jaw. EKG shows ST elevations in leads II, III, and aVF. Coronary angiography reveals 95% occlusion of the right coronary artery (RCA). Which cardiac conduction node is most likely at risk of ischemia in this patient?',
        options: [
          { id: 'A', text: 'Sinoatrial (SA) node only' },
          { id: 'B', text: 'Atrioventricular (AV) node and bundle of His' },
          { id: 'C', text: 'Left bundle branch anterior fascicle' },
          { id: 'D', text: 'Purkinje fibers of the lateral left ventricular wall' },
        ],
        correctOption: 'B',
        explanation: 'In roughly 90% of individuals (right-dominant circulation), the posterior descending artery (PDA) arises from the right coronary artery (RCA). The AV nodal branch arises from the RCA at the crux of the heart, making the AV node highly vulnerable to ischemia during inferior myocardial infarctions.',
      },
      {
        id: 'q-02',
        orderIndex: 2,
        subject: 'Microbiology',
        topic: 'Infectious Disease',
        difficulty: 'medium',
        questionText: 'A 24-year-old female medical student presents with fever, dysuria, and flank pain. Urine culture grows Gram-negative, lactose-fermenting bacilli that are indole-positive and produce pink colonies on MacConkey agar. What is the primary virulence factor responsible for urinary tract adherence in this organism?',
        options: [
          { id: 'A', text: 'Capsular K antigen' },
          { id: 'B', text: 'P fimbriae (pyelonephritis-associated pili)' },
          { id: 'C', text: 'Lipopolysaccharide (Endotoxin)' },
          { id: 'D', text: 'Heat-stable enterotoxin' },
        ],
        correctOption: 'B',
        explanation: 'Uropathogenic Escherichia coli (UPEC) uses P fimbriae to adhere specifically to digalactoside residues (P blood group antigens) on uroepithelial cells and the renal pelvis, facilitating pyelonephritis.',
      },
      {
        id: 'q-03',
        orderIndex: 3,
        subject: 'Biochemistry & Genetics',
        topic: 'Metabolism',
        difficulty: 'hard',
        questionText: 'A 4-month-old male infant is brought to the clinic for developmental delay and failure to thrive. Physical examination reveals hepatomegaly and severe fasting hypoglycemia. Blood tests show lactic acidosis and hyperuricemia. Administration of glucagon fails to increase blood glucose. Deficiency of which enzyme is the primary cause?',
        options: [
          { id: 'A', text: 'Glucose-6-phosphatase (Von Gierke disease)' },
          { id: 'B', text: 'Lysosomal alpha-1,4-glucosidase (Pompe disease)' },
          { id: 'C', text: 'Debranching enzyme (Cori disease)' },
          { id: 'D', text: 'Muscle glycogen phosphorylase (McArdle disease)' },
        ],
        correctOption: 'A',
        explanation: 'Von Gierke disease (Type I Glycogen Storage Disease) is caused by a deficiency of glucose-6-phosphatase. The liver cannot release free glucose from either glycogenolysis or gluconeogenesis, resulting in profound fasting hypoglycemia, severe lactic acidosis, and doll-like facies with hepatomegaly.',
      },
      {
        id: 'q-04',
        orderIndex: 4,
        subject: 'Pharmacology',
        topic: 'Autonomic Nervous System',
        difficulty: 'medium',
        questionText: 'A 63-year-old male with chronic open-angle glaucoma is prescribed a topical eye drop that increases uveoscleral outflow of aqueous humor. Two months later, he notes that his iris has developed a darker brown pigmentation and his eyelashes are noticeably longer and thicker. Which medication was prescribed?',
        options: [
          { id: 'A', text: 'Timolol' },
          { id: 'B', text: 'Latanoprost' },
          { id: 'C', text: 'Pilocarpine' },
          { id: 'D', text: 'Acetazolamide' },
        ],
        correctOption: 'B',
        explanation: 'Latanoprost is a prostaglandin F2-alpha analog that reduces intraocular pressure by increasing uveoscleral outflow. Well-known adverse effects include irreversible brown pigmentation of the iris and hypertrichosis (lengthening and darkening) of eyelashes.',
      },
      {
        id: 'q-05',
        orderIndex: 5,
        subject: 'Immunology',
        topic: 'Hypersensitivity',
        difficulty: 'medium',
        questionText: 'A 32-year-old woman receives an intravenous infusion of ampicillin for acute cellulitis. Within 4 minutes, she develops diffuse urticaria, periorbital angioedema, inspiratory stridor, and blood pressure drops to 78/42 mmHg. Which cell type and cross-linked molecule mediate this acute anaphylactic reaction?',
        options: [
          { id: 'A', text: 'Mast cells / IgE cross-linking on Fc-epsilon-RI' },
          { id: 'B', text: 'Cytotoxic T-lymphocytes / CD8 activation' },
          { id: 'C', text: 'Complement C3b / Neutrophil degranulation' },
          { id: 'D', text: 'Macrophages / IgG immune complexes' },
        ],
        correctOption: 'A',
        explanation: 'Type I Hypersensitivity (Anaphylaxis) occurs when preformed IgE bound to high-affinity Fc-epsilon-RI receptors on mast cells and basophils is cross-linked by antigen, triggering immediate degranulation of histamine, tryptase, and leukotrienes.',
      },
      {
        id: 'q-06',
        orderIndex: 6,
        subject: 'Physiology',
        topic: 'Renal & Electrolytes',
        difficulty: 'hard',
        questionText: 'A 45-year-old male with small cell lung cancer develops confusion and lethargy. Laboratory evaluation shows serum sodium of 118 mEq/L (Normal: 135-145), serum osmolality of 245 mOsm/kg, and urine osmolality of 580 mOsm/kg with urine sodium of 48 mEq/L. He is euvolemic on exam. What is the most appropriate initial pharmacologic therapy?',
        options: [
          { id: 'A', text: 'Rapid infusion of 0.9% normal saline' },
          { id: 'B', text: 'Fluid restriction and Tolvaptan (Vasopressin V2 receptor antagonist)' },
          { id: 'C', text: 'High-dose oral Hydrochlorothiazide' },
          { id: 'D', text: 'Intravenous Dextrose 50% with Insulin' },
        ],
        correctOption: 'B',
        explanation: 'The patient has SIADH (Syndrome of Inappropriate ADH Secretion) secondary to ectopic ADH production from small cell lung cancer. Key findings are euvolemic hyponatremia, high urine osmolality, and elevated urinary sodium. Management includes fluid restriction and V2 receptor antagonists (vaptans).',
      },
    ],
  },
  {
    id: 'tst-02',
    slug: 'imat-italy-biology-chemistry-mock',
    title: 'IMAT Italy Section 2 & 3 High-Yield Simulation',
    category: 'IMAT Italy',
    subject: 'Biology & Chemistry',
    difficulty: 'medium',
    durationMinutes: 30,
    totalQuestions: 4,
    totalMarks: 6,
    positiveMark: 1.5,
    negativeMark: 0.4,
    passingPercentage: 50,
    instructions: 'Simulates Italian Ministry of Education IMAT scoring (+1.5 per correct answer, -0.4 deduction for incorrect answers, 0 for unanswered).',
    isPublicSample: false,
    questions: [
      {
        id: 'q-imat-1',
        orderIndex: 1,
        subject: 'Biology',
        topic: 'Cellular Respiration',
        difficulty: 'medium',
        questionText: 'During aerobic cellular respiration in eukaryotic cells, which of the following processes occurs across the inner mitochondrial membrane?',
        options: [
          { id: 'A', text: 'Glycolysis' },
          { id: 'B', text: 'Electron transport chain and ATP synthesis via proton gradient' },
          { id: 'C', text: 'Citric Acid (Krebs) cycle in the cytoplasm' },
          { id: 'D', text: 'Alcoholic fermentation' },
        ],
        correctOption: 'B',
        explanation: 'The electron transport chain complexes and ATP synthase are located in the inner mitochondrial membrane, pumping protons from the matrix into the intermembrane space.',
      },
      {
        id: 'q-imat-2',
        orderIndex: 2,
        subject: 'Chemistry',
        topic: 'Acid-Base Equilibria',
        difficulty: 'medium',
        questionText: 'What is the pH of a 0.001 M aqueous solution of hydrochloric acid (HCl) at 25°C?',
        options: [
          { id: 'A', text: '1' },
          { id: 'B', text: '3' },
          { id: 'C', text: '7' },
          { id: 'D', text: '11' },
        ],
        correctOption: 'B',
        explanation: 'HCl is a strong acid that completely dissociates. [H+] = 10^-3 M. pH = -log[H+] = -log(10^-3) = 3.',
      },
    ],
  },
];

export const mockUniversities: University[] = [
  {
    id: 'uni-bologna',
    name: 'Università di Bologna',
    italianName: 'Alma Mater Studiorum - Università di Bologna',
    slug: 'universita-di-bologna',
    country: 'Italy',
    city: 'Bologna',
    region: 'North',
    rankingWorld: 133,
    rankingNational: 2,
    tuitionFeeAnnual: 2200,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 9,
    overview: "Founded in 1088, the University of Bologna is the oldest continuously operating university in the Western world. Its English-taught Medicine and Surgery single-cycle MD program integrates cutting-edge translational medicine with clinical training at the world-renowned Policlinico di Sant'Orsola-Malpighi.",
    eligibility: 'High School Diploma with minimum 12 years of schooling, science prerequisites (Biology, Chemistry, Physics/Math), declaration of value / CIMEA statement, and official IMAT test qualification.',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unibo.it/en/teaching/degree-programmes/programme/2026/8415',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 97,
    nonEuSeats: 20,
    hospitalAffiliations: ["Policlinico di Sant'Orsola-Malpighi", 'Ospedale Bellaria', 'Ospedale Maggiore di Bologna'],
    highlights: ['Oldest university in the Western world', "Top European transplant hospital at Sant'Orsola", 'Vibrant international student city'],
    campusLocation: 'Via Massarenti 9, Bologna',
    scholarshipInfo: 'ER.GO regional agency provides tuition waivers, meal grants, and up to €7,200/year living stipends based on ISEE Parificato.',
    historicalCutoffNote: 'Historically one of the highest-demand faculties in northern Italy (~70.5 EU / ~74.3 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)', 'Biomedical Sciences Honors Track'],
  },
  {
    id: 'uni-pavia',
    name: 'Università degli Studi di Pavia',
    italianName: 'Università degli Studi di Pavia',
    slug: 'universita-degli-studi-di-pavia',
    country: 'Italy',
    city: 'Pavia',
    region: 'North',
    rankingWorld: 275,
    rankingNational: 7,
    tuitionFeeAnnual: 2400,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 11,
    overview: 'Home of the historic "Harvey Medicine and Surgery" course, Pavia was the pioneer in establishing English-taught medical education in Italy in 2009. Students train inside the prestigious Fondazione IRCCS Policlinico San Matteo, celebrated for cardiovascular and infectious diseases research.',
    eligibility: 'Minimum 12 years of education, qualifying IMAT score, certified English proficiency (B2 minimum), and consular legalizations.',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://medicina.unipv.it/en/harvey-course/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 103,
    nonEuSeats: 40,
    hospitalAffiliations: ['Fondazione IRCCS Policlinico San Matteo', 'Fondazione Maugeri', 'Istituto Neurologico Casimiro Mondino'],
    highlights: ['First Italian public university to launch English MD (Harvey Course)', 'Compact, collegiate student town only 30 min from Milan', 'World-class robotics & transplant surgery units'],
    campusLocation: 'Corso Strada Nuova 65, Pavia',
    scholarshipInfo: 'EDiSU Pavia manages college accommodations and full regional grants (free boarding + stipend for eligible ISEE).',
    historicalCutoffNote: 'Consistently popular for non-EU and EU applicants (~68.3 EU / ~71.0 Non-EU final cutoff).',
    programs: ['Harvey Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-bari',
    name: 'Università degli Studi di Bari Aldo Moro',
    italianName: 'Università degli Studi di Bari Aldo Moro',
    slug: 'universita-degli-studi-di-bari-aldo-moro',
    country: 'Italy',
    city: 'Bari',
    region: 'South & Islands',
    rankingWorld: 430,
    rankingNational: 16,
    tuitionFeeAnnual: 1700,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 14,
    overview: 'The Bari English Medical Curriculum (BEMC) offers an interactive, patient-centric education in the sunny coastal capital of Apulia. Rotations take place within the extensive Policlinico Consorziale di Bari, one of southern Italys premier tertiary referral hospitals.',
    eligibility: '12 years secondary education, valid passport/visa, IMAT entrance examination pass, DOV or CIMEA equivalence statement.',
    imageUrl: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.uniba.it/ricerca/dipartimenti/dimepre-j/didattica/corsi-di-laurea/bemc',
    lastVerifiedAt: '2026-08-18',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 69,
    nonEuSeats: 11,
    hospitalAffiliations: ['Policlinico Consorziale di Bari', "Ospedale Pediatrico Giovanni XXIII"],
    highlights: ['Cost-effective living in beautiful coastal Puglia', 'Extensive hands-on emergency & pediatric training', 'Close-knit student cohorts with personalized mentorship'],
    campusLocation: 'Piazza Giulio Cesare 11, Bari',
    scholarshipInfo: 'ADISU Puglia regional agency provides full scholarships including free meals, accommodation, and cash stipends.',
    historicalCutoffNote: 'Moderately competitive (~64.2 EU / ~66.8 Non-EU final cutoff).',
    programs: ['Bari English Medical Curriculum - BEMC (MD 6 Years)'],
  },
  {
    id: 'uni-cagliari',
    name: 'Università degli Studi di Cagliari',
    italianName: 'Università degli Studi di Cagliari',
    slug: 'universita-degli-studi-di-cagliari',
    country: 'Italy',
    city: 'Cagliari',
    region: 'South & Islands',
    rankingWorld: 510,
    rankingNational: 20,
    tuitionFeeAnnual: 1800,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 15,
    overview: 'Located on the Mediterranean island of Sardinia, Cagliari features a modern English-taught MD program centered at the Policlinico Universitario Duilio Casula in Monserrato, boasting cutting-edge biomedical research centers and high clinician-to-student ratios.',
    eligibility: '12-year secondary school diploma, IMAT score, legal translations and declaration of value.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://corsi.unica.it/medicinaechirurgiaen/',
    lastVerifiedAt: '2026-08-19',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 80,
    nonEuSeats: 20,
    hospitalAffiliations: ['Policlinico Universitario Duilio Casula (Monserrato)', "Ospedale San Giovanni di Dio"],
    highlights: ['Picturesque island setting with exceptional quality of life', 'State-of-the-art simulation labs in Monserrato', 'Lower cost of living compared to mainland northern Italy'],
    campusLocation: 'Cittadella Universitaria di Monserrato, Cagliari',
    scholarshipInfo: 'ERSU Cagliari regional authority offers grants up to €6,800/year plus free dormitory spots.',
    historicalCutoffNote: 'Friendly cutoff range for well-prepared applicants (~63.5 EU / ~65.1 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-parma',
    name: 'Università degli Studi di Parma',
    italianName: 'Università degli Studi di Parma',
    slug: 'universita-degli-studi-di-parma',
    country: 'Italy',
    city: 'Parma',
    region: 'North',
    rankingWorld: 380,
    rankingNational: 14,
    tuitionFeeAnnual: 2100,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 12,
    overview: 'Parma is renowned for food innovation, culture, and academic heritage. Its English Medicine and Surgery program is situated at the Maggiore Hospital of Parma (Azienda Ospedaliero-Universitaria), a massive regional trauma and neurosurgical hub in the Emilia-Romagna region.',
    eligibility: 'High school graduation with Biology and Chemistry prerequisites, IMAT score, Apostille & CIMEA.',
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://cdl-mc.unipr.it/en',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 75,
    nonEuSeats: 45,
    hospitalAffiliations: ['Azienda Ospedaliero-Universitaria di Parma (Ospedale Maggiore)', 'Ospedale dei Bambini Pietro Barilla'],
    highlights: ['Spacious children hospital Barilla integration', 'High quota of 45 non-EU seats', 'Safe, cycling-friendly gastronomic capital of Italy'],
    campusLocation: 'Via Gramsci 14, Parma',
    scholarshipInfo: 'ER.GO Emilia-Romagna provides generous needs-based grants and housing.',
    historicalCutoffNote: 'Solid, balanced cutoffs (~66.7 EU / ~69.4 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-padova',
    name: 'Università degli Studi di Padova',
    italianName: 'Università degli Studi di Padova',
    slug: 'universita-degli-studi-di-padova',
    country: 'Italy',
    city: 'Padova',
    region: 'North',
    rankingWorld: 120,
    rankingNational: 3,
    tuitionFeeAnnual: 2600,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 9,
    overview: 'Established in 1222, Padua boasts historic anatomy theaters where Andreas Vesalius and William Harvey once taught. Today, it stands as one of Italys most decorated biomedical powerhouses, paired with the Azienda Ospedale Università Padova and Istituto Oncologico Veneto.',
    eligibility: '12 years secondary qualification, IMAT entrance qualification, science background, DOV or CIMEA statement.',
    imageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unipd.it/en/educational-offer/single-cycle-degrees/medicine-and-surgery',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 76,
    nonEuSeats: 25,
    hospitalAffiliations: ['Azienda Ospedale Università Padova', 'Istituto Oncologico Veneto (IOV IRCCS)', 'Ospedale Sant’Antonio'],
    highlights: ['Centuries of anatomical & physiological prestige', 'Major European oncology and organ transplant center', 'Dynamic university city near Venice'],
    campusLocation: 'Via Giustiniani 2, Padova',
    scholarshipInfo: 'ESU Padova provides regional bursaries plus Padova International Excellence Merit scholarships.',
    historicalCutoffNote: 'Consistently high cutoffs reflecting top ranking (~71.8 EU / ~75.2 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-torino',
    name: 'Università degli Studi di Torino',
    italianName: 'Università degli Studi di Torino',
    slug: 'universita-degli-studi-di-torino',
    country: 'Italy',
    city: 'Torino',
    region: 'North',
    rankingWorld: 210,
    rankingNational: 5,
    tuitionFeeAnnual: 2500,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 10,
    overview: 'The University of Turin offers its English MD program within the San Luigi Gonzaga University Hospital complex in Orbassano, with deep connections to the Molinette Hospital and Città della Salute e della Scienza, Europes second-largest hospital complex.',
    eligibility: '12 years schooling, successful IMAT score, valid study visa/permit, English fluency certificate (B2+).',
    imageUrl: 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.medicina-md.unito.it/do/home.pl',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 70,
    nonEuSeats: 32,
    hospitalAffiliations: ['AOU San Luigi Gonzaga (Orbassano)', 'AOU Città della Salute e della Scienza (Molinette)', 'Ospedale Infantile Regina Margherita'],
    highlights: ['Immersion at Città della Salute, Italy’s medical mega-hub', 'Problem-Based Learning (PBL) tutorial approach', 'Vibrant cultural metropolis at the foot of the Alps'],
    campusLocation: 'Regione Gonzole 10, Orbassano (Torino)',
    scholarshipInfo: 'EDISU Piemonte grants provide up to €7,200/year plus restaurant card and university housing.',
    historicalCutoffNote: 'Consistently popular for northern Italy aspirants (~69.5 EU / ~73.0 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-vanvitelli',
    name: 'Università della Campania «Luigi Vanvitelli»',
    italianName: 'Università degli Studi della Campania Luigi Vanvitelli',
    slug: 'universita-della-campania-luigi-vanvitelli',
    country: 'Italy',
    city: 'Caserta / Naples',
    region: 'South & Islands',
    rankingWorld: 490,
    rankingNational: 18,
    tuitionFeeAnnual: 1900,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 16,
    overview: 'Vanvitelli Medicine and Surgery operates in historic Naples and Caserta, blending clinical facilities with an exceptionally supportive international student ecosystem. It boasts one of the highest quotas of non-EU seats (50 seats) among Italian medical faculties.',
    eligibility: '12 years secondary education, IMAT score, CIMEA statement of comparability, Apostille certification.',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.medicinaechirurgia.unicampania.it/en/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 60,
    nonEuSeats: 50,
    hospitalAffiliations: ['Complesso Ospedaliero Policlinico Vanvitelli (Napoli)', "AORN Sant'Anna e San Sebastiano (Caserta)"],
    highlights: ['50 Non-EU seats — highest availability in Italy', 'Very affordable living costs in Caserta and Naples area', 'Rich pathology diversity and patient-facing rotations'],
    campusLocation: 'Via Luciano Armanni 5, Napoli / Caserta',
    scholarshipInfo: 'ADISURC Campania regional agency covers tuition, board, and annual stipends up to €7,000.',
    historicalCutoffNote: 'Accessible cutoff threshold due to high seat count (~62.8 EU / ~64.9 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-padova-medtech',
    name: 'Università degli Studi di Padova — MedTech',
    italianName: 'Università degli Studi di Padova — Medicine and Technology',
    slug: 'universita-degli-studi-di-padova-medtech',
    country: 'Italy',
    city: 'Padova',
    region: 'North',
    rankingWorld: 120,
    rankingNational: 3,
    tuitionFeeAnnual: 2700,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 8,
    overview: 'The MedTech track at University of Padua is a visionary double-degree program delivered jointly by the School of Medicine and the Department of Information & Industrial Engineering. Graduates receive both an MD in Medicine and Surgery and a Bachelor in Biomedical Engineering.',
    eligibility: '12-year secondary education, IMAT qualification, advanced mathematics & scientific background, CIMEA certificate.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unipd.it/en/educational-offer/single-cycle-degrees/medicine-and-surgery-medtech',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 60,
    nonEuSeats: 20,
    hospitalAffiliations: ['Azienda Ospedale Università Padova', 'Padova Bioengineering & Robotics Medical Lab'],
    highlights: ['Double qualification: Medical Doctor (MD) + Bioengineering Degree', 'Pioneering AI in medicine, surgical robotics, and 3D organ printing', 'Elite program tailored for future physician-scientists'],
    campusLocation: 'Via Giustiniani 2 / Via Gradenigo, Padova',
    scholarshipInfo: 'ESU Padova scholarships + Departmental research grants for engineering tracks.',
    historicalCutoffNote: 'High cutoff score reflecting unique tech-medicine dual profile (~73.1 EU / ~76.5 Non-EU final cutoff).',
    programs: ['Medicine & Surgery + Biomedical Engineering (Dual Degree 6 Years)'],
  },
  {
    id: 'uni-tor-vergata',
    name: 'Università di Roma «Tor Vergata»',
    italianName: 'Università degli Studi di Roma Tor Vergata',
    slug: 'universita-di-roma-tor-vergata',
    country: 'Italy',
    city: 'Rome',
    region: 'Central',
    rankingWorld: 290,
    rankingNational: 9,
    tuitionFeeAnnual: 2400,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 11,
    overview: 'Rome Tor Vergata offers an English MD course centered at the ultra-modern Policlinico Tor Vergata (PTV), one of Italys most technologically advanced teaching hospital complexes. It integrates early clinical training, digital simulations, and global clinical rotations.',
    eligibility: 'High school graduation with Biology/Chemistry, IMAT exam score, DOV or CIMEA, legal study clearance.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://medschool.uniroma2.it/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 40,
    nonEuSeats: 15,
    hospitalAffiliations: ['Policlinico Tor Vergata (PTV)', 'Ospedale San Giovanni Calibita Fatebenefratelli'],
    highlights: ['Self-contained campus model with dormitories next to the hospital', 'Advanced emergency, trauma, and genomics departments', 'Located in eternal city Rome with convenient transit links'],
    campusLocation: 'Via Montpellier 1, 00133 Roma',
    scholarshipInfo: 'DiSCo Lazio provides income-based regional grants (€6,500 - €7,200/yr), dining discounts, and accommodation.',
    historicalCutoffNote: 'Solid, competitive cutoffs for Rome location (~68.9 EU / ~72.4 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-milano-statale',
    name: 'Università degli Studi di Milano (La Statale)',
    italianName: 'Università degli Studi di Milano - Statale',
    slug: 'universita-degli-studi-di-milano',
    country: 'Italy',
    city: 'Milan',
    region: 'North',
    rankingWorld: 148,
    rankingNational: 1,
    tuitionFeeAnnual: 2800,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 7,
    overview: 'La Statale hosts the International Medical School (IMS-Milan), widely regarded as the flagship public English medical faculty in Italy. Clinical rotations are hosted across premier hospital centers including ASST Niguarda and San Raffaele, preparing physicians for global careers.',
    eligibility: '12 years secondary education, competitive IMAT score, declaration of value / CIMEA statement, English fluency certificate.',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://ims.cdl.unimi.it/en',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 55,
    nonEuSeats: 25,
    hospitalAffiliations: ['ASST Grande Ospedale Metropolitano Niguarda', 'Ospedale San Raffaele', 'Fondazione IRCCS Ca’ Granda Ospedale Maggiore Policlinico'],
    highlights: ['Flagship English medical course in Italy (IMS-Milan)', 'Top European clinical rotations at Niguarda and Policlinico', 'Situated in Milan, Europe’s leading economic & innovation capital'],
    campusLocation: 'Via Festa del Perdono 7 / Niguarda Hospital, Milano',
    scholarshipInfo: 'DSU Università degli Studi di Milano covers full tuition exemption plus up to €7,300/year living grant.',
    historicalCutoffNote: 'Historically the highest EU cutoff in Italy (~78.2 EU / ~82.5 Non-EU final cutoff).',
    programs: ['International Medical School - IMS (MD 6 Years)'],
  },
  {
    id: 'uni-messina',
    name: 'Università degli Studi di Messina',
    italianName: 'Università degli Studi di Messina',
    slug: 'universita-degli-studi-di-messina',
    country: 'Italy',
    city: 'Messina',
    region: 'South & Islands',
    rankingWorld: 540,
    rankingNational: 22,
    tuitionFeeAnnual: 1600,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 17,
    overview: 'Located on the Sicilian coast overlooking the Strait of Messina, UniMe offers an established English-taught MD program based at Policlinico Universitario Gaetano Martino. It is celebrated for its warm international community and highly accessible living costs.',
    eligibility: '12-year secondary diploma, IMAT score pass, legalizations, CIMEA equivalence.',
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unime.it/it/corsi/laurea-magistrale-ciclo-unico/medicine-and-surgery',
    lastVerifiedAt: '2026-08-18',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 55,
    nonEuSeats: 40,
    hospitalAffiliations: ['Policlinico Universitario Gaetano Martino', 'Ospedale Papardo'],
    highlights: ['Lowest cost of living among Italian medical university cities', '40 Non-EU seats with strong global representation', 'Stunning seaside location with year-round mild Mediterranean climate'],
    campusLocation: 'Via Consolare Valeria 1, Messina',
    scholarshipInfo: 'ERSU Messina provides full housing, canteen cards, and living stipends for eligible students.',
    historicalCutoffNote: 'Accessible cutoff score (~61.9 EU / ~63.8 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-sapienza',
    name: 'Università di Roma «La Sapienza»',
    italianName: 'Sapienza Università di Roma',
    slug: 'universita-di-roma-la-sapienza',
    country: 'Italy',
    city: 'Rome',
    region: 'Central',
    rankingWorld: 132,
    rankingNational: 1,
    tuitionFeeAnnual: 2500,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 8,
    overview: 'Established in 1303 by Pope Boniface VIII, Sapienza is the largest university in Europe by student body. Its English MD program is based directly at the monumental Policlinico Umberto I, one of the most historically significant clinical research centers in southern Europe.',
    eligibility: '12 years secondary qualification, IMAT entrance qualification, Apostille and Declaration of Value (DOV).',
    imageUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://corsidilaurea.uniroma1.it/en/corso/2026/30420/home',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 45,
    nonEuSeats: 13,
    hospitalAffiliations: ['Policlinico Umberto I', 'Azienda Ospedaliera Sant’Andrea'],
    highlights: ['Study in central Rome inside Policlinico Umberto I', 'Vast university library network and extensive specialty departments', 'Top international prestige and academic citations'],
    campusLocation: 'Piazzale Aldo Moro 5 / Viale del Policlinico 155, Roma',
    scholarshipInfo: 'DiSCo Lazio scholarships grant full tuition reimbursement, housing, and stipend.',
    historicalCutoffNote: 'Second-highest historical cutoff after Milan (~72.1 EU / ~76.8 Non-EU final cutoff).',
    programs: ['Medicine and Surgery - Program F (MD 6 Years)'],
  },
  {
    id: 'uni-firenze',
    name: 'Università degli Studi di Firenze',
    italianName: 'Università degli Studi di Firenze',
    slug: 'universita-degli-studi-di-firenze',
    country: 'Italy',
    city: 'Florence',
    region: 'Central',
    rankingWorld: 260,
    rankingNational: 8,
    tuitionFeeAnnual: 2300,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 10,
    overview: 'The University of Florence offers its English Medicine & Surgery program in the historic cradle of the Renaissance. Clinical clerkships are based at the Azienda Ospedaliero-Universitaria Careggi, one of the most modern and comprehensive tertiary care campuses in Tuscany.',
    eligibility: '12 years of education, IMAT score pass, science prerequisites, DOV or CIMEA statement.',
    imageUrl: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.med-chirurgia.unifi.it/vp-267-single-cycle-degree-in-medicine-and-surgery.html',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 35,
    nonEuSeats: 15,
    hospitalAffiliations: ['AOU Careggi (Firenze)', 'AOU Meyer Pediatric Hospital', 'Ospedale San Giovanni di Dio'],
    highlights: ['Clinical rotations at AOU Careggi & renowned Meyer Children’s Hospital', 'Unrivaled cultural experience living in Renaissance Florence', 'Small class cohorts enabling intense bedside tutoring'],
    campusLocation: 'Largo Brambilla 3, Careggi, Firenze',
    scholarshipInfo: 'DSU Toscana regional agency offers grants up to €7,000/year, meal vouchers, and residency hall allocations.',
    historicalCutoffNote: 'Competitive cutoff due to low seat count (~67.4 EU / ~70.9 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-catania',
    name: 'Università degli Studi di Catania',
    italianName: 'Università degli Studi di Catania',
    slug: 'universita-degli-studi-di-catania',
    country: 'Italy',
    city: 'Catania',
    region: 'South & Islands',
    rankingWorld: 480,
    rankingNational: 17,
    tuitionFeeAnnual: 1800,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 15,
    overview: 'Founded in 1434, the University of Catania is the oldest university in Sicily. Its English Medicine and Surgery program is situated at the modern Policlinico G. Rodolico - San Marco, providing students with advanced simulation labs and active clinical exposure in Eastern Sicily.',
    eligibility: '12-year secondary diploma, IMAT score, certified translations, CIMEA statement.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.medicina.unict.it/en/courses/single-cycle-degrees/medicine-and-surgery',
    lastVerifiedAt: '2026-08-19',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 30,
    nonEuSeats: 30,
    hospitalAffiliations: ['Policlinico G. Rodolico - San Marco', 'Ospedale Garibaldi Centro'],
    highlights: ['Balanced 30 EU & 30 Non-EU seat distribution', 'High sunshine hours, vibrant baroque architecture, Etna view', 'Low rent and living expenses for university students'],
    campusLocation: 'Via Santa Sofia 78, Catania',
    scholarshipInfo: 'ERSU Catania manages income-based living bursaries and subsidized university dorms.',
    historicalCutoffNote: 'Balanced cutoffs (~62.4 EU / ~64.5 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-bicocca',
    name: 'Università degli Studi di Milano-Bicocca',
    italianName: 'Università degli Studi di Milano-Bicocca',
    slug: 'universita-degli-studi-di-milano-bicocca',
    country: 'Italy',
    city: 'Bergamo / Milan',
    region: 'North',
    rankingWorld: 230,
    rankingNational: 6,
    tuitionFeeAnnual: 2700,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 8,
    overview: 'Milano-Bicocca operates its English School of Medicine and Surgery (SMS) in Bergamo at the state-of-the-art Papa Giovanni XXIII Hospital. The curriculum is distinguished by Problem-Based Learning (PBL), interprofessional teamwork, and bio-technological research.',
    eligibility: '12-year education diploma, IMAT score, DOV or CIMEA, certified English B2+.',
    imageUrl: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unimib.it/ugov/degree/5685',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 30,
    nonEuSeats: 15,
    hospitalAffiliations: ['Ospedale Papa Giovanni XXIII (Bergamo)', 'Ospedale San Gerardo (Monza)'],
    highlights: ['PBL methodology (small group problem-based learning)', 'Papa Giovanni XXIII Hospital is one of the most technologically advanced in Europe', 'High clinical exposure from year one'],
    campusLocation: 'Piazza OMS 1, Bergamo (Milano-Bicocca SMS)',
    scholarshipInfo: 'DSU Bicocca grants cover full tuition waiver and room/stipend allowances up to €7,300.',
    historicalCutoffNote: 'High cutoff score reflecting small cohort & top hospital (~73.8 EU / ~77.9 Non-EU final cutoff).',
    programs: ['School of Medicine and Surgery - SMS (MD 6 Years)'],
  },
  {
    id: 'uni-federico-ii',
    name: 'Università di Napoli Federico II',
    italianName: 'Università degli Studi di Napoli Federico II',
    slug: 'universita-di-napoli-federico-ii',
    country: 'Italy',
    city: 'Naples',
    region: 'South & Islands',
    rankingWorld: 220,
    rankingNational: 4,
    tuitionFeeAnnual: 2300,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 11,
    overview: 'Founded in 1224 by Holy Roman Emperor Frederick II, this is the worlds oldest state university. The English Medicine & Surgery degree is based at the massive Policlinico Nuovo complex in Naples, renowned for clinical neuroscience, surgical oncology, and cardiovascular care.',
    eligibility: '12 years secondary education, IMAT score, valid study visa, CIMEA comparability statement.',
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.medicina.unina.it/en/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 25,
    nonEuSeats: 25,
    hospitalAffiliations: ['AOU Federico II (Policlinico Nuovo)', 'Ospedale Antonio Cardarelli', 'Istituto Nazionale Tumori Pascale'],
    highlights: ['World’s oldest public state university (800+ years of history)', 'Immense clinical diversity at Policlinico Nuovo', 'Vibrant coastal lifestyle and rich Neapolitan history'],
    campusLocation: 'Via Sergio Pansini 5, Napoli',
    scholarshipInfo: 'ADISURC Campania regional agency provides up to €7,000/year living allowance and free cafeteria.',
    historicalCutoffNote: 'Moderate-to-high cutoffs (~66.0 EU / ~68.2 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-ancona-marche',
    name: 'Università Politecnica delle Marche',
    italianName: 'Università Politecnica delle Marche',
    slug: 'universita-politecnica-delle-marche',
    country: 'Italy',
    city: 'Ancona',
    region: 'Central',
    rankingWorld: 410,
    rankingNational: 15,
    tuitionFeeAnnual: 1950,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 13,
    overview: 'UNIVPM in Ancona on the Adriatic coast provides an English Medicine & Surgery degree embedded in the Ospedali Riuniti di Ancona (Torrette). Known for its biomedical engineering synergy and simulation facilities, it equips students for global medical practice.',
    eligibility: '12 years schooling, successful IMAT score, CIMEA statement or DOV, English B2 proficiency.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.medicina.univpm.it/en/courses/single-cycle-degrees/medicine-and-surgery',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 60,
    nonEuSeats: 25,
    hospitalAffiliations: ['Azienda Ospedaliero-Universitaria delle Marche (Torrette di Ancona)', 'Ospedale Pediatrico Salesi'],
    highlights: ['Modern Torrette hospital campus with high surgical volume', 'Salesi Children’s hospital pediatric clinical training', 'Peaceful coastal lifestyle along the Adriatic Sea'],
    campusLocation: 'Via Tronto 10, Torrette di Ancona',
    scholarshipInfo: 'ERDIS Marche grants provide tuition exemptions, accommodation, and annual cash support.',
    historicalCutoffNote: 'Steady, attainable cutoff scores (~64.9 EU / ~67.2 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  {
    id: 'uni-tor-vergata-tirana',
    name: 'Università di Roma «Tor Vergata» — Tirana campus (Albania)',
    italianName: 'Università Cattolica Nostra Signora del Buon Consiglio (in convenzione con UniRoma Tor Vergata)',
    slug: 'universita-di-roma-tor-vergata-tirana-campus',
    country: 'Albania',
    city: 'Tirana',
    region: 'International',
    rankingWorld: 600,
    rankingNational: 1,
    tuitionFeeAnnual: 9000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English & Italian',
    intakes: ['September / October'],
    admissionRatePercent: 28,
    overview: 'Established in cooperation with Università di Roma Tor Vergata and the University of Milan, this joint medical campus in Tirana offers a dual-recognized medical degree valid across the European Union. Professors from Tor Vergata fly in to teach the identical Italian medical curriculum.',
    eligibility: '12 years secondary education, university-specific entrance examination in sciences/logic, English/Italian proficiency.',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://unizkm.al/en/faculty-of-medicine/medicine-and-surgery/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 50,
    nonEuSeats: 100,
    hospitalAffiliations: ['Catholic University Hospital Our Lady of Good Counsel (Tirana)', 'Policlinico Tor Vergata (Roma clinical rotations)'],
    highlights: ['Italian MD diploma co-signed by University of Rome Tor Vergata', 'No IMAT test required — independent institutional admissions test', 'Rotations available in Rome partner university hospitals'],
    campusLocation: 'Rruga Dritan Hoxha, Tirana, Albania',
    scholarshipInfo: 'Institution-specific merit scholarships and tuition discounts for high entrance test scores.',
    historicalCutoffNote: 'Admitted based on institutional test ranking, high seat availability (100+ seats).',
    programs: ['Medicine and Surgery (EU-accredited Double MD 6 Years)'],
  },
  {
    id: 'uni-siena',
    name: 'Università degli Studi di Siena',
    italianName: 'Università degli Studi di Siena',
    slug: 'universita-degli-studi-di-siena',
    country: 'Italy',
    city: 'Siena',
    region: 'Central',
    rankingWorld: 370,
    rankingNational: 13,
    tuitionFeeAnnual: 2200,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 12,
    overview: 'Founded in 1240 in the heart of medieval Tuscany, the University of Siena delivers medical sciences and dentistry in English alongside medical research at the Azienda Ospedaliero-Universitaria Senese (Policlinico Santa Maria alle Scotte), a leader in cancer immunotherapy.',
    eligibility: '12 years of education, IMAT score pass, certified translation of diploma, DOV / CIMEA.',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://en.unisi.it/ugov/degree/5292',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'IMAT',
    type: 'Public',
    euSeats: 28,
    nonEuSeats: 14,
    hospitalAffiliations: ['Azienda Ospedaliero-Universitaria Senese (Policlinico Le Scotte)', 'Center for Immuno-Oncology (CIO Siena)'],
    highlights: ['World leader in cancer immunotherapy research at Le Scotte', 'Unmatched historical atmosphere in iconic Tuscan city of Siena', 'Intimate academic cohort with focused faculty interaction'],
    campusLocation: 'Strada delle Scotte 4, Siena',
    scholarshipInfo: 'DSU Toscana regional grant covers tuition fee exemption plus living stipends up to €7,000.',
    historicalCutoffNote: 'Moderately competitive (~65.4 EU / ~68.0 Non-EU final cutoff).',
    programs: ['Medicine and Surgery (MD 6 Years)'],
  },
  // Private / specialist Italian medical universities
  {
    id: 'uni-humanitas',
    name: 'Humanitas University',
    italianName: 'Humanitas University',
    slug: 'humanitas-university',
    country: 'Italy',
    city: 'Pieve Emanuele (Milan area)',
    region: 'North',
    rankingWorld: 320,
    rankingNational: 10,
    tuitionFeeAnnual: 18000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 12,
    overview: 'Humanitas University is a research-intensive private medical institution adjacent to the world-renowned Humanitas Research Hospital in the Milan area. Its flagship Medicine & Surgery degree combines an innovative, problem-based curriculum with early patient contact from year one. Humanitas also jointly offers MEDTEC — a unique dual degree combining Medicine with Engineering — in collaboration with Politecnico di Milano.',
    eligibility: '12 years secondary education, science prerequisites, university-specific TOLC-MED or HuCAS entrance examination, English proficiency (B2+).',
    imageUrl: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.hunimed.eu/course/medicine/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 100,
    nonEuSeats: 50,
    hospitalAffiliations: ['Humanitas Research Hospital (IRCCS Humanitas)', 'Humanitas Gavazzeni (Bergamo)', 'Humanitas Mater Domini'],
    highlights: ['Adjacent to IRCCS Humanitas — one of Europe\'s top research hospitals', 'MEDTEC dual degree: Medicine + Engineering with Politecnico di Milano', 'No IMAT required — own entrance test (HuCAS)'],
    campusLocation: 'Via Rita Levi Montalcini 4, 20090 Pieve Emanuele (Milano)',
    scholarshipInfo: 'Merit and needs-based scholarships available for top-scoring applicants; income-based partial waivers offered.',
    historicalCutoffNote: 'Admission based on competitive HuCAS score; approx. 150 total seats per cycle.',
    programs: ['Medicine and Surgery (MD 6 Years)', 'MEDTEC — Medicine & Engineering Dual Degree (with Politecnico di Milano)'],
  },
  {
    id: 'uni-san-raffaele',
    name: 'Vita-Salute San Raffaele University',
    italianName: 'Università Vita-Salute San Raffaele',
    slug: 'vita-salute-san-raffaele-university',
    country: 'Italy',
    city: 'Milan',
    region: 'North',
    rankingWorld: 290,
    rankingNational: 8,
    tuitionFeeAnnual: 20000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 10,
    overview: 'Vita-Salute San Raffaele University, founded by the Don Luigi Monza Institute in Milan, offers the prestigious International Medical Doctor Programme (IMDP) — an elite English-taught MD embedded within the IRCCS Ospedale San Raffaele, recognized globally as a leader in immunology, gene therapy, and transplantation medicine.',
    eligibility: '12 years of secondary education, competitive performance in the university-specific TOLC-MED / SR-IMDP admissions test, science prerequisites, English proficiency C1.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unisr.it/en/offerta-formativa/medicina-chirurgia/international-medical-doctor-program',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 60,
    nonEuSeats: 40,
    hospitalAffiliations: ['IRCCS Ospedale San Raffaele (Milan)', 'San Raffaele Turro', 'San Raffaele Resnati'],
    highlights: ['Clinical training inside IRCCS San Raffaele — Italy\'s #1 research hospital', 'Pioneer in gene therapy, immunology & transplantation medicine', 'International Medical Doctor Programme (IMDP) — elite cohort size'],
    campusLocation: 'Via Olgettina 58, 20132 Milano',
    scholarshipInfo: 'Competitive merit awards and financial aid packages; institutional bursaries for top candidates.',
    historicalCutoffNote: 'Extremely selective; among the highest-ranked private MD programmes in Italy.',
    programs: ['International Medical Doctor Programme — IMDP (MD 6 Years)'],
  },
  {
    id: 'uni-cattolica',
    name: 'Università Cattolica del Sacro Cuore',
    italianName: 'Università Cattolica del Sacro Cuore',
    slug: 'universita-cattolica-del-sacro-cuore',
    country: 'Italy',
    city: 'Rome & Bolzano',
    region: 'Central',
    rankingWorld: 350,
    rankingNational: 12,
    tuitionFeeAnnual: 16000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 13,
    overview: 'One of Italy\'s most prestigious Catholic universities, Università Cattolica del Sacro Cuore offers English-taught Medicine and Surgery at two campuses — its historic Rome campus (Policlinico Agostino Gemelli) and an internationally focused Bolzano campus. The university is renowned for ethics-centered medical education and is affiliated with the Fondazione Policlinico Universitario Gemelli IRCCS, one of Italy\'s premier tertiary care centers.',
    eligibility: '12 years secondary education, TOLC-MED or university-specific test, science prerequisites, English B2+ certification.',
    imageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unicatt.it/corsi/triennale/medicine-and-surgery-roma.html',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 80,
    nonEuSeats: 35,
    hospitalAffiliations: ['Fondazione Policlinico Universitario Agostino Gemelli IRCCS (Rome)', 'Ospedale S. Giovanni Calibita Fatebenefratelli', 'Bolzano Hospital Campus'],
    highlights: ['Dual campus admission: Rome & Bolzano', 'Affiliated with Policlinico Gemelli — rated #1 Catholic hospital in Italy', 'Strong ethics, humanities, and global medicine framework'],
    campusLocation: 'Largo Francesco Vito 1, Roma / Bolzano Campus',
    scholarshipInfo: 'Catholic University Foundation scholarships; merit-based partial tuition reductions and alumni donor bursaries.',
    historicalCutoffNote: 'Highly sought-after; Rome campus typically more competitive than Bolzano.',
    programs: ['Medicine and Surgery (MD 6 Years) — Rome Campus', 'Medicine and Surgery (MD 6 Years) — Bolzano Campus'],
  },
  {
    id: 'uni-campus-biomed',
    name: 'Università Campus Bio-Medico di Roma',
    italianName: 'Università Campus Bio-Medico di Roma',
    slug: 'universita-campus-bio-medico-di-roma',
    country: 'Italy',
    city: 'Rome',
    region: 'Central',
    rankingWorld: 480,
    rankingNational: 18,
    tuitionFeeAnnual: 15000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 20,
    overview: 'Università Campus Bio-Medico di Roma (UCBM) is a Catholic-inspired private university offering both a standard English-taught Medicine & Surgery degree and a pioneering MedTech programme — the first in Rome to integrate medical education with clinical bioengineering and healthcare technology, delivered inside its own Bio-Medico Hospital.',
    eligibility: '12 years secondary education, TOLC-MED or university entrance exam, science prerequisites, English B2+ certification.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unicampus.it/en/ammissioni-corsi-di-laurea/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 70,
    nonEuSeats: 30,
    hospitalAffiliations: ['Policlinico Universitario Campus Bio-Medico (Rome)', 'Fondazione Campus Bio-Medico Clinical Research Institute'],
    highlights: ['MedTech programme: Medicine + clinical engineering & health tech in English', 'Self-contained campus model with on-site teaching hospital', 'Innovative interdisciplinary research in robotic surgery & diagnostics'],
    campusLocation: 'Via Álvaro del Portillo 21, 00128 Roma',
    scholarshipInfo: 'Income-based bursaries and merit scholarships offered by the university foundation.',
    historicalCutoffNote: 'More accessible than Humanitas/San Raffaele; competitive within its own entrance test.',
    programs: ['Medicine and Surgery (MD 6 Years)', 'MedTech — Medicine & Biomedical Engineering (English, 6 Years)'],
  },
  {
    id: 'uni-unicamillus',
    name: 'UniCamillus — Saint Camillus International University of Health Sciences',
    italianName: 'UniCamillus — Università Internazionale delle Scienze della Salute',
    slug: 'unicamillus-international-university',
    country: 'Italy',
    city: 'Rome',
    region: 'Central',
    rankingWorld: 620,
    rankingNational: 24,
    tuitionFeeAnnual: 14500,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October', 'February (limited)'],
    admissionRatePercent: 30,
    overview: 'UniCamillus is a young, internationally focused private medical university in Rome, specifically designed for non-Italian students seeking to study Medicine in English. Its curriculum follows the LM-41 framework and leads to a fully EU-recognized MD degree. The university prides itself on a multicultural student community, flexible intake periods, and English-only teaching from day one.',
    eligibility: '12 years secondary education, university-specific entrance examination (TOLC-MED or UniCamillus Aptitude Test), English B2+ proficiency.',
    imageUrl: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://unicamillus.org/en/courses/msc/medicine-and-surgery-rome/',
    lastVerifiedAt: '2026-08-20',
    isFeatured: false,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 80,
    nonEuSeats: 80,
    hospitalAffiliations: ['Campus Bio-Medico Affiliated Teaching Hospitals', 'Ospedali Riuniti Partner Network (Rome)'],
    highlights: ['Designed primarily for international non-Italian English-speaking students', 'No IMAT required — own English aptitude test', 'EU-recognised MD (LM-41) degree from Rome'],
    campusLocation: 'Via di Sant\'Alessandro 8, 00131 Roma',
    scholarshipInfo: 'Limited merit-based partial scholarships; early enrollment discounts available.',
    historicalCutoffNote: 'Admission based on competitive test rank; among the more accessible private options in Rome.',
    programs: ['Medicine and Surgery (MSc LM-41, 6 Years) — Rome Campus (English)'],
  },
  {
    id: 'uni-unineuromed',
    name: 'UniNeuromed',
    italianName: 'UniNeuromed — Università degli Studi del Molise (Medicina)',
    slug: 'unineuromed-molise',
    country: 'Italy',
    city: 'Pozzilli, Molise',
    region: 'South & Islands',
    rankingWorld: 700,
    rankingNational: 26,
    tuitionFeeAnnual: 12000,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 40,
    overview: 'UniNeuromed is a brand new English-medium medical university for 2026/27 located in Pozzilli, Molise, adjacent to the IRCCS Neuromed institute — one of Italy\'s leading centres for neurological disease research. It represents the newest accredited English Medicine & Surgery pathway in Italy, officially launching its first admission call for the 2026/27 academic year. EU medical degree (LM-41) fully recognized across Europe.',
    eligibility: '12 years of secondary school education, university-specific entrance exam (2026/27 admission call published), science prerequisites, English proficiency certificate.',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unineuromed.it/corsi-di-laurea/medicine-and-surgery/',
    lastVerifiedAt: '2026-09-01',
    isFeatured: false,
    admissionRoute: 'University-specific',
    type: 'Private',
    euSeats: 50,
    nonEuSeats: 50,
    hospitalAffiliations: ['IRCCS Neuromed (Pozzilli)', 'Policlinico di Campobasso', 'Neuromed Clinical Research Network'],
    highlights: ['NEW for 2026/27 — first intake: founding cohort opportunity', 'Adjacent to IRCCS Neuromed — Italy\'s #1 neuroscience research institute', 'Lower tuition and living costs vs. northern Italy private universities'],
    campusLocation: 'Via Atinense 18, 86077 Pozzilli (IS), Molise',
    scholarshipInfo: 'Founding cohort early-bird merit scholarships anticipated; tuition discounts for high test scorers.',
    historicalCutoffNote: 'New 2026/27 — no historical cutoff data; first admission call published. Accessible entry opportunity.',
    programs: ['Medicine and Surgery (MD LM-41, 6 Years) — New 2026/27'],
  },
];

export const mockScholarships: Scholarship[] = [
  {
    id: 'sch-01',
    title: 'Italian DSU / ER.GO Regional Government Full Grant',
    country: 'Italy',
    universityName: 'All Public Italian Universities',
    coverageAmount: '€7,200/yr + 100% Tuition Waiver + Free Meals',
    coverageType: 'Full Tuition + Living Stipend',
    eligibilitySummary: 'Based on Family ISEE Parificato economic indicator (< €26,000/yr) and academic progression credits.',
    deadline: '2026-09-05',
    lastVerifiedAt: '2026-08-20',
  },
  {
    id: 'sch-02',
    title: 'Stipendium Hungaricum Medical Excellence Award',
    country: 'Hungary',
    universityName: 'Semmelweis, Debrecen, Szeged',
    coverageAmount: 'Full Tuition ($18,200/yr) + Housing + Medical Insurance',
    coverageType: 'Full Tuition + Accommodation',
    eligibilitySummary: 'Bilateral educational agreement nomination and entrance exam ranking.',
    deadline: '2026-11-15',
    lastVerifiedAt: '2026-08-15',
  },
  {
    id: 'sch-03',
    title: 'Ahsora Meds Academic Merit Scholarship',
    country: 'Global',
    universityName: 'Partner Medical Programs',
    coverageAmount: '$3,000 - $6,000 One-time Award',
    coverageType: 'Partial Tuition Assistance',
    eligibilitySummary: 'Top 5% score in Ahsora Diagnostic Mock Exams & verified admissions offer.',
    deadline: '2026-10-30',
    lastVerifiedAt: '2026-08-28',
  },
];

export const mockMentors: Mentor[] = [
  {
    id: 'men-01',
    name: 'Dr. Sarah Jenkins, MD',
    title: 'US Residency Consultant & USMLE Mentor',
    specialization: 'Internal Medicine / Cardiology',
    qualifications: 'MD Harvard Medical School, USMLE Step 1 (264), Step 2 CK (271)',
    experienceYears: 8,
    bio: 'Mentored over 400 IMGs matching into top tier US university hospital programs. Expert in clinical vignette deconstruction and ERAS application strategy.',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    rating: 4.98,
    totalSessions: 520,
    hourlyRate: 85,
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
  },
  {
    id: 'men-02',
    name: 'Dr. Marco Rossi',
    title: 'Senior Faculty & IMAT Exam Lead',
    specialization: 'Human Anatomy & European Admissions',
    qualifications: 'MD, PhD University of Milan IMS, Former Admissions Reviewer',
    experienceYears: 10,
    bio: 'Lead author of the Ahsora IMAT preparation curriculum. Guided 250+ non-EU students into top Italian medical faculties.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    rating: 4.95,
    totalSessions: 680,
    hourlyRate: 75,
    availableDays: ['Tuesday', 'Thursday', 'Sunday'],
  },
];

export const mockDoubts: DoubtItem[] = [
  {
    id: 'dbt-01',
    studentName: 'Demo Student',
    subject: 'Cardiovascular Pathology',
    topic: 'Myocardial Infarction Complications',
    title: 'Ventricular septal rupture vs Papillary muscle rupture murmur timing',
    questionText: 'How can I quickly differentiate acute VSR from acute papillary muscle rupture in a Step 1 vignette when both present with sudden pulmonary edema and a holosystolic murmur?',
    status: 'resolved',
    assignedMentorName: 'Dr. Sarah Jenkins, MD',
    resolutionNote: 'Look for oxygen saturation step-up in the right ventricle (indicates VSR due to left-to-right shunt). Papillary muscle rupture shows prominent v-waves on pulmonary capillary wedge pressure tracing without RV O2 step-up.',
    createdAt: '2026-08-28T14:20:00Z',
  },
  {
    id: 'dbt-02',
    studentName: 'Demo Student',
    subject: 'Renal Physiology',
    topic: 'Acid-Base Disorders',
    title: 'Winter formula calculation on mixed disorders',
    questionText: 'When expected PaCO2 is higher than calculated Winters formula range, what secondary disorder is present?',
    status: 'open',
    assignedMentorName: 'Dr. Marco Rossi',
    createdAt: '2026-08-30T18:10:00Z',
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'ld-01',
    leadCode: 'LEAD-2026-881',
    name: 'Zainab Al-Mansoor',
    email: 'zainab.m@example.com',
    phone: '+971 50 123 4567',
    country: 'United Arab Emirates',
    city: 'Dubai',
    academicBackground: 'IB Diploma (Predicted 41/45)',
    targetExam: 'IMAT / Italy MBBS',
    targetCountry: 'Italy',
    budgetRange: '€5,000 - €10,000/yr',
    source: 'Google Search (Organic)',
    utmSource: 'seo_universities_italy',
    assignedCounsellor: 'Elena Vance (Senior Counsellor)',
    stage: 'counselling_booked',
    priority: 'hot',
    leadScore: 92,
    nextFollowupAt: '2026-09-02T10:00:00Z',
    notes: 'Very strong candidate. Parents interested in Milan and Pavia. Scheduled zoom consultation.',
    createdAt: '2026-08-29T11:30:00Z',
  },
  {
    id: 'ld-02',
    leadCode: 'LEAD-2026-882',
    name: 'Tariq Mehmood',
    email: 'tariq.m99@example.com',
    phone: '+92 300 8765432',
    country: 'Pakistan',
    city: 'Lahore',
    academicBackground: 'FSc Pre-Medical (91%)',
    targetExam: 'USMLE Step 1 & Hungary MD',
    targetCountry: 'Hungary / USA',
    budgetRange: '$15,000 - $20,000/yr',
    source: 'Facebook Ad Campaign',
    utmSource: 'fb_semmelweis_promo',
    assignedCounsellor: 'David Ross',
    stage: 'qualified',
    priority: 'warm',
    leadScore: 78,
    nextFollowupAt: '2026-09-03T15:00:00Z',
    notes: 'Requested Semmelweis entrance exam mock materials and fee structure.',
    createdAt: '2026-08-30T09:15:00Z',
  },
  {
    id: 'ld-03',
    leadCode: 'LEAD-2026-883',
    name: 'Sophia Chen',
    email: 'sophia.chen@example.ca',
    phone: '+1 416 987 6543',
    country: 'Canada',
    city: 'Toronto',
    academicBackground: 'BSc Neuroscience (UofT)',
    targetExam: 'PLAB 1 / UK GMC Registration',
    targetCountry: 'United Kingdom',
    budgetRange: '£10,000 - £18,000/yr',
    source: 'Direct Website Enquiry',
    assignedCounsellor: 'Elena Vance',
    stage: 'proposal_sent',
    priority: 'hot',
    leadScore: 88,
    nextFollowupAt: '2026-09-01T17:00:00Z',
    notes: 'Reviewing PLAB 1 full residency support package.',
    createdAt: '2026-08-27T16:00:00Z',
  },
];

export const mockApplicationCases: ApplicationCase[] = [
  {
    id: 'app-case-01',
    caseNumber: 'AHS-2026-IT-901',
    studentName: 'Demo Student',
    targetCountry: 'Italy',
    targetIntake: 'Academic Year 2026/2027 (Sept)',
    currentStage: 'application_prepared',
    assignedCounsellor: 'Elena Vance',
    assignedAdmissionsOfficer: 'Marcus Sterling',
    progressPercent: 65,
    createdAt: '2026-02-10T08:00:00Z',
    applications: [
      {
        id: 'sub-app-01',
        universityName: 'University of Milan (La Statale)',
        program: 'Medicine and Surgery (English IMD)',
        status: 'application_prepared',
        deadline: '2026-09-18',
      },
      {
        id: 'sub-app-02',
        universityName: 'Sapienza University of Rome',
        program: 'Medicine and Surgery (English)',
        status: 'documents_pending',
        deadline: '2026-09-22',
      },
    ],
  },
];

export const mockStudentDocuments: StudentDocument[] = [
  {
    id: 'doc-01',
    category: 'identity_passport',
    title: 'International Passport (Bio Page)',
    fileName: 'Passport_DemoStudent_2026.pdf',
    fileSizeBytes: 2450000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-12T10:00:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
  {
    id: 'doc-02',
    category: 'academic_certificate',
    title: 'High School Diploma & Official Transcript',
    fileName: 'HS_Transcript_Apostilled.pdf',
    fileSizeBytes: 4890000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-14T12:30:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
  {
    id: 'doc-03',
    category: 'language_certificate',
    title: 'IELTS Academic Official Test Report (Band 8.0)',
    fileName: 'IELTS_ScoreReport_Student.pdf',
    fileSizeBytes: 1820000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-18T09:15:00Z',
    reviewedBy: 'Elena Vance (Counsellor)',
  },
  {
    id: 'doc-04',
    category: 'financial_document',
    title: 'Family ISEE Parificato Economic Declaration',
    fileName: 'ISEE_Financial_Declaration_Draft.pdf',
    fileSizeBytes: 3200000,
    status: 'under_review',
    version: 2,
    uploadedAt: '2026-08-29T16:45:00Z',
  },
  {
    id: 'doc-05',
    category: 'attestation_legalization',
    title: 'Declaration of Value (DOV) / CIMEA Statement of Comparability',
    fileName: 'CIMEA_Comparability_Receipt.pdf',
    fileSizeBytes: 1450000,
    status: 'revision_requested',
    rejectionReason: 'Please attach the full 4-page certified translation with Italian notary stamp.',
    version: 1,
    uploadedAt: '2026-08-25T14:10:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
];

export const mockVisaCases: VisaCase[] = [
  {
    id: 'visa-01',
    destinationCountry: 'Italy',
    visaType: 'National Type D Student Visa (Long Stay)',
    status: 'appointment_booked',
    officerName: 'Sophia Ricci (Senior Visa Specialist)',
    appointmentDate: '2026-09-12T09:30:00Z',
    submissionDate: '2026-09-12',
    notes: 'Universitaly pre-enrolment summary verified. Financial sponsorship bank statements exceed the €6,000 threshold requirement.',
    checklists: [
      { item: 'Universitaly Summary Form (Validated by UniMi)', isCompleted: true },
      { item: 'Flight Itinerary Reservation', isCompleted: true },
      { item: 'Schengen Area Medical Insurance (€30,000 minimum)', isCompleted: true },
      { item: 'Accommodation Proof / Housing Contract in Milan', isCompleted: true },
      { item: 'Bank Account Balance & Sponsor Tax Returns', isCompleted: true },
      { item: 'VFS Visa Appointment Slip & Bio Form', isCompleted: true },
    ],
  },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'aud-01',
    actorName: 'Marcus Sterling',
    actorRole: 'admissions_officer',
    action: 'DOCUMENT_STATUS_UPDATED',
    entityType: 'Document (doc-05)',
    details: 'Changed status to revision_requested with note: Please attach full certified translation.',
    timestamp: '2026-08-29T14:10:00Z',
  },
  {
    id: 'aud-02',
    actorName: 'Elena Vance',
    actorRole: 'counsellor',
    action: 'LEAD_STAGE_UPDATED',
    entityType: 'Lead (ld-01)',
    details: 'Moved lead Zainab Al-Mansoor from qualified to counselling_booked.',
    timestamp: '2026-08-29T11:35:00Z',
  },
  {
    id: 'aud-03',
    actorName: 'Super Admin',
    actorRole: 'super_admin',
    action: 'COURSE_PRICE_UPDATED',
    entityType: 'Product (USMLE Step 1)',
    details: 'Updated base price from $750 to $699 in centralized pricing registry.',
    timestamp: '2026-08-28T09:00:00Z',
  },
];

export const mockSchedules: ScheduleItem[] = [];

export const mockRecordedLectures: RecordedLecture[] = [];

export const mockLibraryResources: LibraryResource[] = [];

export const mockStudentMistakes: StudentMistake[] = [];


