import {
  Course,
  Test,
  University,
  Scholarship,
  Mentor,
  DoubtItem,
  Lead,
  ApplicationCase,
  StudentDocument,
  VisaCase,
  AuditLogItem,
  Profile,
} from '@/types';

export const mockCurrentUser: Profile = {
  id: 'usr-student-01',
  role: 'student',
  firstName: 'Arham',
  lastName: 'Farooq',
  email: 'arham.farooq@student.ahsora.com',
  phone: '+1 (555) 234-8901',
  country: 'United States',
  city: 'Chicago',
  targetExam: 'USMLE Step 1 / IMAT Italy',
  targetCountry: 'Italy / USA',
  isVerified: true,
  createdAt: '2026-01-15T09:00:00Z',
};

export const mockCourses: Course[] = [
  {
    id: 'crs-01',
    slug: 'usmle-step-1-complete-mastery',
    title: 'USMLE Step 1: Clinical Integrated High-Yield Mastery',
    category: 'Medical Licensure',
    targetExam: 'USMLE Step 1',
    summary: 'Organ systems, pharmacology, pathology, and high-yield question breakdowns with top US residency mentors.',
    overview: 'This comprehensive course provides an organ-systems approach with integrated pathology, pharmacology, and physiology. Designed for medical students targeting top residency percentiles.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    durationHours: 140,
    totalLectures: 86,
    totalTests: 12,
    totalResources: 45,
    rating: 4.96,
    studentsCount: 1420,
    price: 699,
    comparePrice: 999,
    isFeatured: true,
    badge: 'Bestseller',
    modules: [
      {
        id: 'mod-01',
        title: 'Cardiovascular Pathology & Hemodynamics',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-01',
            title: 'Ischemic Heart Disease: EKG & Biomarkers',
            durationMinutes: 42,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            contentMarkdown: '### Key Concepts in Ischemic Heart Disease\n\n1. **STEMI vs NSTEMI**\n- Transmural vs subendocardial infarction.\n- Troponin I and T rise within 2-4 hours, peak at 24 hours, persist for 7-10 days.\n\n2. **EKG Localization**\n- Anterior (LAD): V1-V4\n- Lateral (LCX): I, aVL, V5, V6\n- Inferior (RCA): II, III, aVF',
            isPreviewAllowed: true,
            isCompleted: true,
            orderIndex: 1,
          },
          {
            id: 'les-02',
            title: 'Valvular Heart Disease & Murmur Diagnostics',
            durationMinutes: 38,
            videoUrl: '',
            contentMarkdown: '### Systolic vs Diastolic Murmurs\n\n- **Aortic Stenosis**: Crescendo-decrescendo systolic ejection murmur at right 2nd ICS radiating to carotids.\n- **Mitral Regurgitation**: Holosystolic, high-pitched "blowing" murmur best heard at apex radiating to axilla.',
            isPreviewAllowed: false,
            isCompleted: true,
            orderIndex: 2,
          },
          {
            id: 'les-03',
            title: 'Heart Failure & Renin-Angiotensin System',
            durationMinutes: 50,
            videoUrl: '',
            contentMarkdown: '### Pathophysiology of Congestive Heart Failure\n\nDecreased cardiac output activates the sympathetic nervous system and the RAAS axis.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 3,
          },
        ],
      },
      {
        id: 'mod-02',
        title: 'Renal & Acid-Base Physiology',
        orderIndex: 2,
        lessons: [
          {
            id: 'les-04',
            title: 'Glomerular Filtration Rate & Clearance Mechanics',
            durationMinutes: 35,
            videoUrl: '',
            contentMarkdown: '### GFR and Renal Clearance Equations\n\nClearance = (Urine Concentration * Urine Flow) / Plasma Concentration.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 1,
          },
          {
            id: 'les-05',
            title: 'High Anion Gap Metabolic Acidosis (MUDPILES)',
            durationMinutes: 44,
            videoUrl: '',
            contentMarkdown: '### MUDPILES Differential Diagnosis\nMethanol, Uremia, DKA, Propylene glycol, Iron/INH, Lactic acidosis, Ethylene glycol, Salicylates.',
            isPreviewAllowed: false,
            isCompleted: false,
            orderIndex: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'crs-02',
    slug: 'imat-italy-medical-entrance-prep',
    title: 'IMAT Italy: Complete Public Medical University Prep',
    category: 'Medical Admissions',
    targetExam: 'IMAT (Italy)',
    summary: 'Biology, Chemistry, Physics, Math, and Critical Reasoning specifically tailored to the Italian Ministry of Education entrance exam.',
    overview: 'Official preparation program for admission to English-taught medical faculties across Italy (Milan, Rome La Sapienza, Bologna, Pavia, Padua).',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&auto=format&fit=crop&q=80',
    durationHours: 110,
    totalLectures: 64,
    totalTests: 18,
    totalResources: 38,
    rating: 4.94,
    studentsCount: 980,
    price: 499,
    comparePrice: 750,
    isFeatured: true,
    badge: 'Popular',
    modules: [
      {
        id: 'mod-10',
        title: 'Cellular Biology & Molecular Genetics',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-10',
            title: 'Mendelian Genetics & Non-Mendelian Inheritance',
            durationMinutes: 30,
            isPreviewAllowed: true,
            isCompleted: true,
            orderIndex: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'crs-03',
    slug: 'plab-1-uk-gmc-registration-masterclass',
    title: 'PLAB 1 / UKMLA Clinical Knowledge Masterclass',
    category: 'Medical Licensure',
    targetExam: 'PLAB 1 / UKMLA',
    summary: 'NICE guidelines, GMC Good Medical Practice, emergency management, and single-best-answer strategy for UK practice.',
    overview: 'Targeted preparation for international medical graduates aiming to practice within the UK National Health Service (NHS).',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80',
    durationHours: 95,
    totalLectures: 52,
    totalTests: 10,
    totalResources: 30,
    rating: 4.91,
    studentsCount: 820,
    price: 449,
    comparePrice: 599,
    isFeatured: false,
    badge: 'NHS Aligned',
    modules: [],
  },
  {
    id: 'crs-04',
    slug: 'medical-german-b2-c1-approbation',
    title: 'Medical German B2/C1 & FSP Approbation Program',
    category: 'Language & Residency',
    targetExam: 'FSP / KP (Germany)',
    summary: 'Doctor-patient communication, medical history taking (Anamnese), and clinical documentation for German medical licensure.',
    overview: 'Comprehensive preparation for the Fachsprachenprüfung (FSP) and Kenntnisprüfung (KP) for medical residency in Germany.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    durationHours: 120,
    totalLectures: 70,
    totalTests: 8,
    totalResources: 50,
    rating: 4.98,
    studentsCount: 610,
    price: 799,
    comparePrice: 1100,
    isFeatured: true,
    badge: 'High Demand',
    modules: [],
  },
];

export const mockTests: Test[] = [
  {
    id: 'tst-01',
    slug: 'usmle-step-1-diagnostic-mock-01',
    title: 'USMLE Step 1 Full Diagnostic Assessment - Block 1',
    category: 'USMLE Step 1',
    subject: 'Integrated Medical Sciences',
    difficulty: 'hard',
    durationMinutes: 45,
    totalQuestions: 6,
    totalMarks: 24,
    positiveMark: 4,
    negativeMark: 1,
    passingPercentage: 60,
    instructions: 'This block contains 6 high-yield vignette questions. Timed at 45 minutes with standard 1-minute/question pacing. Negative marking is applied (-1 for incorrect, +4 for correct).',
    isPublicSample: true,
    questions: [
      {
        id: 'q-01',
        orderIndex: 1,
        subject: 'Pathology & Pharmacology',
        topic: 'Cardiovascular',
        difficulty: 'hard',
        questionText: 'A 58-year-old male presents with severe retrosternal chest tightness radiating to the left jaw. EKG shows ST elevations in leads II, III, and aVF. Coronary angiography reveals 95% occlusion of the right coronary artery (RCA). Which cardiac conduction node is most likely at risk of ischemia in this patient?',
        options: [
          { id: 'A', text: 'Sinoatrial (SA) node only' },
          { id: 'B', text: 'Atrioventricular (AV) node and bundle of His' },
          { id: 'C', text: 'Left bundle branch anterior fascicle' },
          { id: 'D', text: 'Purkinje fibers of the lateral left ventricular wall' },
        ],
        correctOption: 'B',
        explanation: 'In roughly 90% of individuals (right-dominant circulation), the posterior descending artery (PDA) arises from the right coronary artery (RCA). The AV nodal branch arises from the RCA at the crux of the heart, making the AV node highly vulnerable to ischemia during inferior myocardial infarctions.',
      },
      {
        id: 'q-02',
        orderIndex: 2,
        subject: 'Microbiology',
        topic: 'Infectious Disease',
        difficulty: 'medium',
        questionText: 'A 24-year-old female medical student presents with fever, dysuria, and flank pain. Urine culture grows Gram-negative, lactose-fermenting bacilli that are indole-positive and produce pink colonies on MacConkey agar. What is the primary virulence factor responsible for urinary tract adherence in this organism?',
        options: [
          { id: 'A', text: 'Capsular K antigen' },
          { id: 'B', text: 'P fimbriae (pyelonephritis-associated pili)' },
          { id: 'C', text: 'Lipopolysaccharide (Endotoxin)' },
          { id: 'D', text: 'Heat-stable enterotoxin' },
        ],
        correctOption: 'B',
        explanation: 'Uropathogenic Escherichia coli (UPEC) uses P fimbriae to adhere specifically to digalactoside residues (P blood group antigens) on uroepithelial cells and the renal pelvis, facilitating pyelonephritis.',
      },
      {
        id: 'q-03',
        orderIndex: 3,
        subject: 'Biochemistry & Genetics',
        topic: 'Metabolism',
        difficulty: 'hard',
        questionText: 'A 4-month-old male infant is brought to the clinic for developmental delay and failure to thrive. Physical examination reveals hepatomegaly and severe fasting hypoglycemia. Blood tests show lactic acidosis and hyperuricemia. Administration of glucagon fails to increase blood glucose. Deficiency of which enzyme is the primary cause?',
        options: [
          { id: 'A', text: 'Glucose-6-phosphatase (Von Gierke disease)' },
          { id: 'B', text: 'Lysosomal alpha-1,4-glucosidase (Pompe disease)' },
          { id: 'C', text: 'Debranching enzyme (Cori disease)' },
          { id: 'D', text: 'Muscle glycogen phosphorylase (McArdle disease)' },
        ],
        correctOption: 'A',
        explanation: 'Von Gierke disease (Type I Glycogen Storage Disease) is caused by a deficiency of glucose-6-phosphatase. The liver cannot release free glucose from either glycogenolysis or gluconeogenesis, resulting in profound fasting hypoglycemia, severe lactic acidosis, and doll-like facies with hepatomegaly.',
      },
      {
        id: 'q-04',
        orderIndex: 4,
        subject: 'Pharmacology',
        topic: 'Autonomic Nervous System',
        difficulty: 'medium',
        questionText: 'A 63-year-old male with chronic open-angle glaucoma is prescribed a topical eye drop that increases uveoscleral outflow of aqueous humor. Two months later, he notes that his iris has developed a darker brown pigmentation and his eyelashes are noticeably longer and thicker. Which medication was prescribed?',
        options: [
          { id: 'A', text: 'Timolol' },
          { id: 'B', text: 'Latanoprost' },
          { id: 'C', text: 'Pilocarpine' },
          { id: 'D', text: 'Acetazolamide' },
        ],
        correctOption: 'B',
        explanation: 'Latanoprost is a prostaglandin F2-alpha analog that reduces intraocular pressure by increasing uveoscleral outflow. Well-known adverse effects include irreversible brown pigmentation of the iris and hypertrichosis (lengthening and darkening) of eyelashes.',
      },
      {
        id: 'q-05',
        orderIndex: 5,
        subject: 'Immunology',
        topic: 'Hypersensitivity',
        difficulty: 'medium',
        questionText: 'A 32-year-old woman receives an intravenous infusion of ampicillin for acute cellulitis. Within 4 minutes, she develops diffuse urticaria, periorbital angioedema, inspiratory stridor, and blood pressure drops to 78/42 mmHg. Which cell type and cross-linked molecule mediate this acute anaphylactic reaction?',
        options: [
          { id: 'A', text: 'Mast cells / IgE cross-linking on Fc-epsilon-RI' },
          { id: 'B', text: 'Cytotoxic T-lymphocytes / CD8 activation' },
          { id: 'C', text: 'Complement C3b / Neutrophil degranulation' },
          { id: 'D', text: 'Macrophages / IgG immune complexes' },
        ],
        correctOption: 'A',
        explanation: 'Type I Hypersensitivity (Anaphylaxis) occurs when preformed IgE bound to high-affinity Fc-epsilon-RI receptors on mast cells and basophils is cross-linked by antigen, triggering immediate degranulation of histamine, tryptase, and leukotrienes.',
      },
      {
        id: 'q-06',
        orderIndex: 6,
        subject: 'Physiology',
        topic: 'Renal & Electrolytes',
        difficulty: 'hard',
        questionText: 'A 45-year-old male with small cell lung cancer develops confusion and lethargy. Laboratory evaluation shows serum sodium of 118 mEq/L (Normal: 135-145), serum osmolality of 245 mOsm/kg, and urine osmolality of 580 mOsm/kg with urine sodium of 48 mEq/L. He is euvolemic on exam. What is the most appropriate initial pharmacologic therapy?',
        options: [
          { id: 'A', text: 'Rapid infusion of 0.9% normal saline' },
          { id: 'B', text: 'Fluid restriction and Tolvaptan (Vasopressin V2 receptor antagonist)' },
          { id: 'C', text: 'High-dose oral Hydrochlorothiazide' },
          { id: 'D', text: 'Intravenous Dextrose 50% with Insulin' },
        ],
        correctOption: 'B',
        explanation: 'The patient has SIADH (Syndrome of Inappropriate ADH Secretion) secondary to ectopic ADH production from small cell lung cancer. Key findings are euvolemic hyponatremia, high urine osmolality, and elevated urinary sodium. Management includes fluid restriction and V2 receptor antagonists (vaptans).',
      },
    ],
  },
  {
    id: 'tst-02',
    slug: 'imat-italy-biology-chemistry-mock',
    title: 'IMAT Italy Section 2 & 3 High-Yield Simulation',
    category: 'IMAT Italy',
    subject: 'Biology & Chemistry',
    difficulty: 'medium',
    durationMinutes: 30,
    totalQuestions: 4,
    totalMarks: 6,
    positiveMark: 1.5,
    negativeMark: 0.4,
    passingPercentage: 50,
    instructions: 'Simulates Italian Ministry of Education IMAT scoring (+1.5 per correct answer, -0.4 deduction for incorrect answers, 0 for unanswered).',
    isPublicSample: false,
    questions: [
      {
        id: 'q-imat-1',
        orderIndex: 1,
        subject: 'Biology',
        topic: 'Cellular Respiration',
        difficulty: 'medium',
        questionText: 'During aerobic cellular respiration in eukaryotic cells, which of the following processes occurs across the inner mitochondrial membrane?',
        options: [
          { id: 'A', text: 'Glycolysis' },
          { id: 'B', text: 'Electron transport chain and ATP synthesis via proton gradient' },
          { id: 'C', text: 'Citric Acid (Krebs) cycle in the cytoplasm' },
          { id: 'D', text: 'Alcoholic fermentation' },
        ],
        correctOption: 'B',
        explanation: 'The electron transport chain complexes and ATP synthase are located in the inner mitochondrial membrane, pumping protons from the matrix into the intermembrane space.',
      },
      {
        id: 'q-imat-2',
        orderIndex: 2,
        subject: 'Chemistry',
        topic: 'Acid-Base Equilibria',
        difficulty: 'medium',
        questionText: 'What is the pH of a 0.001 M aqueous solution of hydrochloric acid (HCl) at 25°C?',
        options: [
          { id: 'A', text: '1' },
          { id: 'B', text: '3' },
          { id: 'C', text: '7' },
          { id: 'D', text: '11' },
        ],
        correctOption: 'B',
        explanation: 'HCl is a strong acid that completely dissociates. [H+] = 10^-3 M. pH = -log[H+] = -log(10^-3) = 3.',
      },
    ],
  },
];

export const mockUniversities: University[] = [
  {
    id: 'uni-01',
    name: 'University of Milan (La Statale)',
    slug: 'university-of-milan',
    country: 'Italy',
    city: 'Milan',
    rankingWorld: 148,
    rankingNational: 2,
    tuitionFeeAnnual: 1800,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September / October'],
    admissionRatePercent: 12,
    overview: 'One of Europes premier public medical faculties offering the English-taught International Medical School (IMS-Milan) at San Raffaele and Niguarda clinical teaching hospitals.',
    eligibility: 'High School Diploma with minimum 12 years of education, science prerequisites (Biology/Chemistry), and IMAT entrance exam score.',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.unimi.it/en/education/medicine-and-surgery',
    lastVerifiedAt: '2026-08-15',
    isFeatured: true,
    programs: ['Medicine & Surgery (MD 6 Years)', 'Dentistry & Dental Prosthodontics'],
  },
  {
    id: 'uni-02',
    name: 'Sapienza University of Rome',
    slug: 'sapienza-university-of-rome',
    country: 'Italy',
    city: 'Rome',
    rankingWorld: 132,
    rankingNational: 1,
    tuitionFeeAnnual: 2200,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September'],
    admissionRatePercent: 10,
    overview: 'Founded in 1303, Sapienza is the largest European university with an internationally acclaimed English MD program at Policlinico Umberto I hospital complex.',
    eligibility: '12 years schooling, Apostille certification, Declaration of Value (DOV), and IMAT qualification.',
    imageUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.uniroma1.it/en',
    lastVerifiedAt: '2026-08-20',
    isFeatured: true,
    programs: ['Medicine & Surgery (Policlinico)', 'Pharmacy & Biotechnology'],
  },
  {
    id: 'uni-03',
    name: 'Semmelweis University',
    slug: 'semmelweis-university',
    country: 'Hungary',
    city: 'Budapest',
    rankingWorld: 240,
    rankingNational: 1,
    tuitionFeeAnnual: 18200,
    currency: 'USD',
    durationYears: 6.0,
    language: 'English',
    intakes: ['September'],
    admissionRatePercent: 35,
    overview: 'Central Europes leading biomedical institution with over 250 years of medical training tradition, fully recognized across the EU, USMLE, and GMC.',
    eligibility: 'High School biology/chemistry, entrance written test, and oral interview.',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://semmelweis.hu/english/',
    lastVerifiedAt: '2026-08-10',
    isFeatured: true,
    programs: ['General Medicine (Dr. Med. Univ.)', 'Dentistry (DMD)'],
  },
  {
    id: 'uni-04',
    name: 'Tbilisi State Medical University',
    slug: 'tbilisi-state-medical-university',
    country: 'Georgia',
    city: 'Tbilisi',
    rankingWorld: 650,
    rankingNational: 1,
    tuitionFeeAnnual: 8000,
    currency: 'USD',
    durationYears: 6.0,
    language: 'English',
    intakes: ['March', 'September'],
    admissionRatePercent: 65,
    overview: 'WFME and WHO recognized medical faculty offering USMD and international MD programs in English with US-partnered clinical rotations.',
    eligibility: 'High school graduation with Biology and Chemistry, English interview.',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://tsmu.edu/',
    lastVerifiedAt: '2026-08-18',
    isFeatured: false,
    programs: ['USMD Program (Emory Partnered)', 'International MD Program'],
  },
  {
    id: 'uni-05',
    name: 'Charité - Universitätsmedizin Berlin',
    slug: 'charite-berlin',
    country: 'Germany',
    city: 'Berlin',
    rankingWorld: 45,
    rankingNational: 1,
    tuitionFeeAnnual: 750,
    currency: 'EUR',
    durationYears: 6.0,
    language: 'German (B2/C1)',
    intakes: ['October'],
    admissionRatePercent: 5,
    overview: 'One of the largest university hospitals in Europe, producing over half of all German Nobel laureates in Physiology or Medicine.',
    eligibility: 'German Abitur or equivalent (Abitur-Anerkennung), TestAS score, German Goethe/TestDaF C1.',
    imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&auto=format&fit=crop&q=80',
    officialWebsiteUrl: 'https://www.charite.de/en/',
    lastVerifiedAt: '2026-08-25',
    isFeatured: true,
    programs: ['Modellstudiengang Medizin (Staatsexamen)'],
  },
];

export const mockScholarships: Scholarship[] = [
  {
    id: 'sch-01',
    title: 'Italian DSU / ER.GO Regional Government Full Grant',
    country: 'Italy',
    universityName: 'All Public Italian Universities',
    coverageAmount: '€7,200/yr + 100% Tuition Waiver + Free Meals',
    coverageType: 'Full Tuition + Living Stipend',
    eligibilitySummary: 'Based on Family ISEE Parificato economic indicator (< €26,000/yr) and academic progression credits.',
    deadline: '2026-09-05',
    lastVerifiedAt: '2026-08-20',
  },
  {
    id: 'sch-02',
    title: 'Stipendium Hungaricum Medical Excellence Award',
    country: 'Hungary',
    universityName: 'Semmelweis, Debrecen, Szeged',
    coverageAmount: 'Full Tuition ($18,200/yr) + Housing + Medical Insurance',
    coverageType: 'Full Tuition + Accommodation',
    eligibilitySummary: 'Bilateral educational agreement nomination and entrance exam ranking.',
    deadline: '2026-11-15',
    lastVerifiedAt: '2026-08-15',
  },
  {
    id: 'sch-03',
    title: 'Ahsora Meds Academic Merit Scholarship',
    country: 'Global',
    universityName: 'Partner Medical Programs',
    coverageAmount: '$3,000 - $6,000 One-time Award',
    coverageType: 'Partial Tuition Assistance',
    eligibilitySummary: 'Top 5% score in Ahsora Diagnostic Mock Exams & verified admissions offer.',
    deadline: '2026-10-30',
    lastVerifiedAt: '2026-08-28',
  },
];

export const mockMentors: Mentor[] = [
  {
    id: 'men-01',
    name: 'Dr. Sarah Jenkins, MD',
    title: 'US Residency Consultant & USMLE Mentor',
    specialization: 'Internal Medicine / Cardiology',
    qualifications: 'MD Harvard Medical School, USMLE Step 1 (264), Step 2 CK (271)',
    experienceYears: 8,
    bio: 'Mentored over 400 IMGs matching into top tier US university hospital programs. Expert in clinical vignette deconstruction and ERAS application strategy.',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    rating: 4.98,
    totalSessions: 520,
    hourlyRate: 85,
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
  },
  {
    id: 'men-02',
    name: 'Dr. Marco Rossi',
    title: 'Senior Faculty & IMAT Exam Lead',
    specialization: 'Human Anatomy & European Admissions',
    qualifications: 'MD, PhD University of Milan IMS, Former Admissions Reviewer',
    experienceYears: 10,
    bio: 'Lead author of the Ahsora IMAT preparation curriculum. Guided 250+ non-EU students into top Italian medical faculties.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    rating: 4.95,
    totalSessions: 680,
    hourlyRate: 75,
    availableDays: ['Tuesday', 'Thursday', 'Sunday'],
  },
];

export const mockDoubts: DoubtItem[] = [
  {
    id: 'dbt-01',
    studentName: 'Arham Farooq',
    subject: 'Cardiovascular Pathology',
    topic: 'Myocardial Infarction Complications',
    title: 'Ventricular septal rupture vs Papillary muscle rupture murmur timing',
    questionText: 'How can I quickly differentiate acute VSR from acute papillary muscle rupture in a Step 1 vignette when both present with sudden pulmonary edema and a holosystolic murmur?',
    status: 'resolved',
    assignedMentorName: 'Dr. Sarah Jenkins, MD',
    resolutionNote: 'Look for oxygen saturation step-up in the right ventricle (indicates VSR due to left-to-right shunt). Papillary muscle rupture shows prominent v-waves on pulmonary capillary wedge pressure tracing without RV O2 step-up.',
    createdAt: '2026-08-28T14:20:00Z',
  },
  {
    id: 'dbt-02',
    studentName: 'Arham Farooq',
    subject: 'Renal Physiology',
    topic: 'Acid-Base Disorders',
    title: 'Winter formula calculation on mixed disorders',
    questionText: 'When expected PaCO2 is higher than calculated Winters formula range, what secondary disorder is present?',
    status: 'open',
    assignedMentorName: 'Dr. Marco Rossi',
    createdAt: '2026-08-30T18:10:00Z',
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'ld-01',
    leadCode: 'LEAD-2026-881',
    name: 'Zainab Al-Mansoor',
    email: 'zainab.m@example.com',
    phone: '+971 50 123 4567',
    country: 'United Arab Emirates',
    city: 'Dubai',
    academicBackground: 'IB Diploma (Predicted 41/45)',
    targetExam: 'IMAT / Italy MBBS',
    targetCountry: 'Italy',
    budgetRange: '€5,000 - €10,000/yr',
    source: 'Google Search (Organic)',
    utmSource: 'seo_universities_italy',
    assignedCounsellor: 'Elena Vance (Senior Counsellor)',
    stage: 'counselling_booked',
    priority: 'hot',
    leadScore: 92,
    nextFollowupAt: '2026-09-02T10:00:00Z',
    notes: 'Very strong candidate. Parents interested in Milan and Pavia. Scheduled zoom consultation.',
    createdAt: '2026-08-29T11:30:00Z',
  },
  {
    id: 'ld-02',
    leadCode: 'LEAD-2026-882',
    name: 'Tariq Mehmood',
    email: 'tariq.m99@example.com',
    phone: '+92 300 8765432',
    country: 'Pakistan',
    city: 'Lahore',
    academicBackground: 'FSc Pre-Medical (91%)',
    targetExam: 'USMLE Step 1 & Hungary MD',
    targetCountry: 'Hungary / USA',
    budgetRange: '$15,000 - $20,000/yr',
    source: 'Facebook Ad Campaign',
    utmSource: 'fb_semmelweis_promo',
    assignedCounsellor: 'David Ross',
    stage: 'qualified',
    priority: 'warm',
    leadScore: 78,
    nextFollowupAt: '2026-09-03T15:00:00Z',
    notes: 'Requested Semmelweis entrance exam mock materials and fee structure.',
    createdAt: '2026-08-30T09:15:00Z',
  },
  {
    id: 'ld-03',
    leadCode: 'LEAD-2026-883',
    name: 'Sophia Chen',
    email: 'sophia.chen@example.ca',
    phone: '+1 416 987 6543',
    country: 'Canada',
    city: 'Toronto',
    academicBackground: 'BSc Neuroscience (UofT)',
    targetExam: 'PLAB 1 / UK GMC Registration',
    targetCountry: 'United Kingdom',
    budgetRange: '£10,000 - £18,000/yr',
    source: 'Direct Website Enquiry',
    assignedCounsellor: 'Elena Vance',
    stage: 'proposal_sent',
    priority: 'hot',
    leadScore: 88,
    nextFollowupAt: '2026-09-01T17:00:00Z',
    notes: 'Reviewing PLAB 1 full residency support package.',
    createdAt: '2026-08-27T16:00:00Z',
  },
];

export const mockApplicationCases: ApplicationCase[] = [
  {
    id: 'app-case-01',
    caseNumber: 'AHS-2026-IT-901',
    studentName: 'Arham Farooq',
    targetCountry: 'Italy',
    targetIntake: 'Academic Year 2026/2027 (Sept)',
    currentStage: 'application_prepared',
    assignedCounsellor: 'Elena Vance',
    assignedAdmissionsOfficer: 'Marcus Sterling',
    progressPercent: 65,
    createdAt: '2026-02-10T08:00:00Z',
    applications: [
      {
        id: 'sub-app-01',
        universityName: 'University of Milan (La Statale)',
        program: 'Medicine and Surgery (English IMD)',
        status: 'application_prepared',
        deadline: '2026-09-18',
      },
      {
        id: 'sub-app-02',
        universityName: 'Sapienza University of Rome',
        program: 'Medicine and Surgery (English)',
        status: 'documents_pending',
        deadline: '2026-09-22',
      },
    ],
  },
];

export const mockStudentDocuments: StudentDocument[] = [
  {
    id: 'doc-01',
    category: 'identity_passport',
    title: 'International Passport (Bio Page)',
    fileName: 'Passport_ArhamFarooq_2026.pdf',
    fileSizeBytes: 2450000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-12T10:00:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
  {
    id: 'doc-02',
    category: 'academic_certificate',
    title: 'High School Diploma & Official Transcript',
    fileName: 'HS_Transcript_Apostilled.pdf',
    fileSizeBytes: 4890000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-14T12:30:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
  {
    id: 'doc-03',
    category: 'language_certificate',
    title: 'IELTS Academic Official Test Report (Band 8.0)',
    fileName: 'IELTS_ScoreReport_Arham.pdf',
    fileSizeBytes: 1820000,
    status: 'approved',
    version: 1,
    uploadedAt: '2026-02-18T09:15:00Z',
    reviewedBy: 'Elena Vance (Counsellor)',
  },
  {
    id: 'doc-04',
    category: 'financial_document',
    title: 'Family ISEE Parificato Economic Declaration',
    fileName: 'ISEE_Financial_Declaration_Draft.pdf',
    fileSizeBytes: 3200000,
    status: 'under_review',
    version: 2,
    uploadedAt: '2026-08-29T16:45:00Z',
  },
  {
    id: 'doc-05',
    category: 'attestation_legalization',
    title: 'Declaration of Value (DOV) / CIMEA Statement of Comparability',
    fileName: 'CIMEA_Comparability_Receipt.pdf',
    fileSizeBytes: 1450000,
    status: 'revision_requested',
    rejectionReason: 'Please attach the full 4-page certified translation with Italian notary stamp.',
    version: 1,
    uploadedAt: '2026-08-25T14:10:00Z',
    reviewedBy: 'Marcus Sterling (Admissions)',
  },
];

export const mockVisaCases: VisaCase[] = [
  {
    id: 'visa-01',
    destinationCountry: 'Italy',
    visaType: 'National Type D Student Visa (Long Stay)',
    status: 'appointment_booked',
    officerName: 'Sophia Ricci (Senior Visa Specialist)',
    appointmentDate: '2026-09-12T09:30:00Z',
    submissionDate: '2026-09-12',
    notes: 'Universitaly pre-enrolment summary verified. Financial sponsorship bank statements exceed the €6,000 threshold requirement.',
    checklists: [
      { item: 'Universitaly Summary Form (Validated by UniMi)', isCompleted: true },
      { item: 'Flight Itinerary Reservation', isCompleted: true },
      { item: 'Schengen Area Medical Insurance (€30,000 minimum)', isCompleted: true },
      { item: 'Accommodation Proof / Housing Contract in Milan', isCompleted: true },
      { item: 'Bank Account Balance & Sponsor Tax Returns', isCompleted: true },
      { item: 'VFS Visa Appointment Slip & Bio Form', isCompleted: true },
    ],
  },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'aud-01',
    actorName: 'Marcus Sterling',
    actorRole: 'admissions_officer',
    action: 'DOCUMENT_STATUS_UPDATED',
    entityType: 'Document (doc-05)',
    details: 'Changed status to revision_requested with note: Please attach full certified translation.',
    timestamp: '2026-08-29T14:10:00Z',
  },
  {
    id: 'aud-02',
    actorName: 'Elena Vance',
    actorRole: 'counsellor',
    action: 'LEAD_STAGE_UPDATED',
    entityType: 'Lead (ld-01)',
    details: 'Moved lead Zainab Al-Mansoor from qualified to counselling_booked.',
    timestamp: '2026-08-29T11:35:00Z',
  },
  {
    id: 'aud-03',
    actorName: 'Super Admin',
    actorRole: 'super_admin',
    action: 'COURSE_PRICE_UPDATED',
    entityType: 'Product (USMLE Step 1)',
    details: 'Updated base price from $750 to $699 in centralized pricing registry.',
    timestamp: '2026-08-28T09:00:00Z',
  },
];
